### ISSUE TITLE
Example from README doesn't work: "Cannot invoke method invoke() on null object"

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [etiennestuder/gradle-jooq-plugin#10]
I tried to run the example from the README file, but even when just executing `gradle` I get the error

```
$ gradle

FAILURE: Build failed with an exception.

* Where:
Build file '/home/moritz/workspace/foo/backend/build.gradle' line: 66

* What went wrong:
A problem occurred evaluating root project 'backend'.
> Cannot invoke method invoke() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.757 secs
```

It seems it doesn't like the `sample(sourceSets.main)` line since `sample` is not defined anywhere. I'm using Gradle 2.9 on Linux.

**Comment by jschaf** [comment]
I just ran into this problem as well with Gradle 2.5 on Windows.

**Comment by etiennestuder** [comment]
I cannot reproduce the problem. Can you provide a full, executable sample build?

**Comment by aleksey-zhidkov** [comment]
In my case the same error was caused by paste of `database` block outside of `generator` block.

**Comment by etiennestuder** [comment]
I believe you configured something wrong within the `sample` block.
