### ISSUE TITLE
Option to set generated task name

### ISSUE THREAD

**Issue by amirabiri** [etiennestuder/gradle-jooq-plugin#101]
In our workflow we don't run the generate task automatically, as that slows down the build unnecessarily. We break the bond with compileJava and run the task manually:

    afterEvaluate {
        compileJava.dependsOn -= "generateXXXJooqSchemaSource"
    }

And when we change the schema:

    # gradle generateXXXJooqSchemaSource

This task name is rather cumbersome. What about an option in the plugins DSL to determine the resulting task's name?

    jooq {
        xxx(sourceSets.main) {
            taskName 'jooqGenerate'
            jdbc {
                ...
            }
            generator {
                ...
            }
        }
    }

**Comment by etiennestuder** [comment]
In your build, you can declare a task instance with a custom name (e.g. `runJooq`) that depends on the default task added by the jooq plugin (e.g. `generateXXXJooqSchemaSource`). You can then invoke your custom task.
