### ISSUE TITLE
Add support for jooq 3.12.x

### ISSUE THREAD

**Issue by ieugen** [etiennestuder/gradle-jooq-plugin#104]
Hello,

I'm using your plugin wiht jooq 3.12.x and I get a lot of warnings of deprecated fields.
My build is failing right not but I am not sure if it is because of the plugin:

```
ls.JooqLogger warn
WARNING: DEPRECATED               : The <expression/> element in <forcedType/> is deprecated. Use <includeExpression/> instead: <userType>java.util.Map</userType><binding>gr8pi.jooq.databindings.jackson.converters.AnswersBinding</binding><includeExpression>.*\.answers.*</includeExpression><types>.*jsonb.*</types><nullability>ALL</nullability><objectType>ALL</objectType>

```

**Comment by alex-lx** [comment]
Just for anyone who met this issue, there's a workaround I tried which works for our project.
Explicitly specify the jooq dependency in `buildscript` block, see the following code:
```gradle
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url("https://plugins.gradle.org/m2/") }
    }
    dependencies {
        classpath "org.jooq:jooq-codegen:3.12.1"
    }
}
```

**Comment by etiennestuder** [comment]
The README explains how to set a different jooq version. Plugin version 4.0 will use 3.12.3 by default.
