### ISSUE TITLE
Missing JooqEdition

### ISSUE THREAD

**Issue by tomort** [etiennestuder/gradle-jooq-plugin#111]
I'm working with Jooq 3.12.2 pro-java-8.
Missing the entry in the edition enum.
With 'PRO' the plugin did not work.
How can I fix that?

**Comment by etiennestuder** [comment]
Please provide a detailed bug report incl. a reproducible example if you want your issue to be considered.

**Comment by etiennestuder** [comment]
Closing since no further details were provided.
