### ISSUE TITLE
README.md: update to version 4.1

### ISSUE THREAD

**Issue by GreenT13** [etiennestuder/gradle-jooq-plugin#112]
On the main page it says:
```
plugins {
	id 'nu.studer.jooq' version '4.0'
}
```
However, later on in the page you indicate that the boolean "generateSchemaSourceOnCompilation" can be used. I copy and pasted everything from the README.md, leading to errors locally that it didn't exist. Took me a minute to figure out it was only implemented in 4.1!

To avoid this problem for other people, please update the page :)

**Comment by etiennestuder** [comment]
Fixed. A PR would have been great.
