### ISSUE TITLE
Compatibility with jooq 3.6.0

### ISSUE THREAD

**Issue by tomakita** [etiennestuder/gradle-jooq-plugin#113]
Hi,

Thanks for the great plugin!  Do you know if gradle-jooq-plugin is compatible with jooq version 3.6.0?  I see a note in the changelog about upgrading to 3.6.2, but I don't see any mention of 3.6.0 anywhere.  When I try to use gradle-jooq-plugin (version 2.0.11) with jooq 3.6.0, I get the following exception when attempting to generate code:

> java.lang.ClassNotFoundException: org.jooq.meta.mysql.MySQLDatabase
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at org.jooq.util.GenerationTool.loadClass(GenerationTool.java:492)
>         at org.jooq.util.GenerationTool.run(GenerationTool.java:241)
>         at org.jooq.util.GenerationTool.generate(GenerationTool.java:176)
>         at org.jooq.util.GenerationTool.main(GenerationTool.java:151)

And I just wanted to check to see if this is a compatibility issue, or something that I have misconfigured on my machine.

Thanks!

**Comment by lukaseder** [comment]
At the time, the class was called `org.jooq.util.mysql.MySQLDatabase`, see: https://www.jooq.org/doc/3.6/manual/code-generation/codegen-configuration

The package names had to be renamed in both `jOOQ-meta` and `jOOQ-codegen` for JPMS compliance, because of a split `org.jooq.util` package.

**Comment by tomakita** [comment]
Ok, thanks Lukas!
