### ISSUE TITLE
Gradle 'compile' directive deprecated

### ISSUE THREAD

**Issue by royaldark** [etiennestuder/gradle-jooq-plugin#114]
The current configuration in the README uses `compile` in the `dependencies`, which is deprecated and will be removed in Gradle 7.

Config:
```
dependencies {
  compile 'org.jooq:jooq'
}
```

Message:
```
The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation configuration instead.
```

I switched `compile` to `implementation` and it seemed to work fine. I'm not a Gradle expert though, so not sure if that will work in all cases?

**Comment by isaac-weisberg** [comment]
This is not the problem with the plugin, but rather, dated documentation. You should use implementation and it will work in all cases.

**Comment by etiennestuder** [comment]
Fixed in [this commit](https://github.com/etiennestuder/gradle-jooq-plugin/commit/6d4972a2ed759d87cf4ef02c2bce9c0271986d91). It's unfortunate that in general people only point out issues with no intention to provide a PR that fixes it.
