### ISSUE TITLE
Update version enum to support the changed groups

### ISSUE THREAD

**Issue by CDPrete** [etiennestuder/gradle-jooq-plugin#115]
Seems like that the JOOQ team released a version for Java 9 and, in doing so, they changed the `pro` group-id to `pro-java-8`: https://www.jooq.org/doc/3.12/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/#N529B6

It needs to be reflected in the `JooqEdition` enum :)

**Comment by etiennestuder** [comment]
@CDPrete Happy to accept a PR for the fix incl. test coverage.

**Comment by lukaseder** [comment]
Good point, sorry for the missing communications here!

Our strategy is this:

- The jOOQ Open Source Edition will always have the `org.jooq` groupId and module name
- The jOOQ Trial Edition will always have the `org.jooq.trial` groupId and module name, although, starting from 3.13, we'll also ship
  - `org.jooq.trial-java-6` to try out the Java 6-7 distribution
  - `org.jooq.trial-java-8` to try out the Java 8 distribution
- The jOOQ Professional Edition and Enterprise Edition have these distributions
  - `org.jooq.pro-java-6` for the Java 6-7 distribution
  - `org.jooq.pro-java-8` for the Java 8 distribution
  - `org.jooq.pro` for the latest supported Java distribution (currently Java 11)

**Comment by CDPrete** [comment]
> @CDPrete Happy to accept a PR for the fix incl. test coverage.

I think I can leave with the Java 11 version, so I'll try to open a PR as soon as I've time

**Comment by ayedo** [comment]
Hello everybody, I wanted to use the trial version for java 8 with the plugin, but I get: 

`could not find org.jooq.trial:jooq-codegen:3.13.1.`

This looks like it might be related to this issue here?

I've tried downloading the java 6 version of the trial but it also has changed the group name to org.jooq.trial-java-6

I've subscribed for the third time to a trial to download the java 11 version, and only that one has the name found in the enum.

**Comment by lukaseder** [comment]
I've created a PR here: https://github.com/etiennestuder/gradle-jooq-plugin/pull/122

> I've tried downloading the java 6 version of the trial but it also has changed the group name to org.jooq.trial-java-6

There was no such trial distribution before jOOQ 3.12.4. The Java requirement of the `org.jooq.trial` always corresponds to that of `org.jooq.pro`, which got raised to Java 11 in jOOQ 3.12.0.

**Comment by etiennestuder** [comment]
I've merged @lukaseder's PR. This will be available in 4.2.
