### ISSUE TITLE
Kotlin DSL for v4.0 and v4.1 is currently broken

### ISSUE THREAD

**Issue by kiddouk** [etiennestuder/gradle-jooq-plugin#116]
I got to give this plugin a go and got to dive into the source code as to why the plugin example is currently broken for v4.0 and v4.1.

Indeed, `JooqExtensionsExts` didn't carry the changes required when migrating to jooq 3.12.0 in v4.0. In the provided code, the import at [this line](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/buildSrc/src/main/kotlin/JooqExtensionExts.kt#L22) implicitely expects a class `Schema` whereas [newer versions of jooq](https://github.com/jOOQ/jOOQ/blob/version-3.13.1/jOOQ-meta/src/main/java/org/jooq/meta/jaxb/SchemaMappingType.java#L28) migrated this class to `SchemaMappingType`.

Cheers,

**Comment by etiennestuder** [comment]
As of 5.x, the gradle-jooq-plugin supports the Gradle Kotlin DSL as a first-class citizen. See the README file:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md

See this complete example written with the Gradle Kotlin DSL:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts
