### ISSUE TITLE
Changes in schema not detected

### ISSUE THREAD

**Issue by jkubos** [etiennestuder/gradle-jooq-plugin#119]
It seem to me that gradle-jooq-plugin does not react on schema change. When I for example add column to database and then run task generateNavigoJooqSchemaSource it is considered not changed and therefore not executed. It seems this guy has same issue https://stackoverflow.com/questions/60415391/how-to-perform-a-jooq-code-re-generation/60633318

We have two workarounds to clean state before running tasks - see my comment on Stackoverflow.

Config and log attached, can you please take a look?

[config.txt](https://github.com/etiennestuder/gradle-jooq-plugin/files/4318163/config.txt)
[log.txt](https://github.com/etiennestuder/gradle-jooq-plugin/files/4318164/log.txt)

What other information you need to investigate?

Thank you!

**Comment by jkubos** [comment]
Sorry, wrong log attached. Check this one.

[log.txt](https://github.com/etiennestuder/gradle-jooq-plugin/files/4318217/log.txt)

**Comment by etiennestuder** [comment]
Yes, the jOOQ task does not check the DB schema for changes. That would be very expensive to do in terms of build time. It is up to each build to define additional task inputs that trigger the jOOQ task when needed. For example, by adding the flyway schema migration files as inputs to the jOOQ task.
