### ISSUE TITLE
Don't use buildscript {} for dependencies

### ISSUE THREAD

**Issue by oehme** [etiennestuder/gradle-jooq-plugin#12]
Using `buildscript` to load the jooq dependencies has several problems:

- we want to encourage users to use `plugins` instead of `buildscript`
- child projects can't alter their jooq classpath if the parent has set up the tasks
- there's potential for dependency conflicts because `buildscript` also contains all other libraries on the script's classpath

Instead the plugin should add a dependency configuration and load jooq dynamically from there:

```
dependencies {
  jooqGenerator 'some-version-of-jooq'
  jooqGenerator 'some-db-driver'
}
```

Another advantage is that this way it would be trivial to add a forked mode for when users need more control over the generation process.

**Comment by etiennestuder** [comment]
Fixed by PR https://github.com/etiennestuder/gradle-jooq-plugin/pull/20. Will be part of the upcoming 2.0.0 version.
