### ISSUE TITLE
Kotlin DSL example doesn't compile

### ISSUE THREAD

**Issue by luispollo** [etiennestuder/gradle-jooq-plugin#120]
With Gradle 6.3, the example using the Kotlin DSL does not compile for me, with the following error:
```
  Line 083:   "sample"(sourceSets["main"]) {
              ^ Expression '"sample"' of type 'String' cannot be invoked as a function. The function 'invoke()' is not found
```

...which is this line:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/8b2716dbc5f14811c55fa83ba8796e0358974d7c/example/use_kotlin_dsl/build.gradle.kts#L19

Looking at the code, my guess is that the Kotlin DSL cannot handle the Groovy `methodMissing` implementation you used, but I'm not sure. Did this example work for you and, if so, on what version of Gradle?

Thanks for putting the plugin together, BTW!

**Comment by ssuchkov** [comment]
same here, it works if you explicitly invoke functions

it looks a bit ugly, but works for me

`jooq {
    version = "3.12.3"
    edition = JooqEdition.OSS
    methodMissing("db", arrayOf(sourceSets["main"],
        closureOf<nu.studer.gradle.util.JaxbConfigurationBridge> {
            propertyMissing(
                "jdbc", org.jooq.meta.jaxb.Jdbc()
                    .withDriver("org.h2.Driver")
                    .withUrl("jdbc:h2:~/test;AUTO_SERVER=TRUE")
                    .withUser("sa")
                    .withPassword("sags")
            )
            propertyMissing(
                "generator", org.jooq.meta.jaxb.Generator()
                    .withName("org.jooq.codegen.DefaultGenerator")
                    .withDatabase(
                        org.jooq.meta.jaxb.Database()
                            .withName("org.jooq.meta.h2.H2Database")
                            .withIncludes(".*")
                            .withExcludes("")
                    )
                    .withGenerate(
                        org.jooq.meta.jaxb.Generate()
                            .withDeprecated(false)
                            .withRecords(false)
                            .withImmutablePojos(false)
                            .withFluentSetters(false)
                    )
                    .withTarget(
                        org.jooq.meta.jaxb.Target()
                            .withPackageName("com.generated.db")
                    )
                    .withStrategy(
                        org.jooq.meta.jaxb.Strategy()
                            .withName("org.jooq.codegen.DefaultGeneratorStrategy")
                    )
            )
        }
    ))
}
`

**Comment by etiennestuder** [comment]
The jOOQ plugin is not designed to work with the Kotlin DSL. You can either
- [follow this example to configure the jOOQ plugin with Groovy in your Kotlin DSL Gradle build](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/use_kotlin_dsl_with_groovy) or
- [follow this example to configure the jOOQ plugin with Kotlin in your Kotlin DSL Gradle build](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/use_kotlin_dsl)

**Comment by kowy** [comment]
Solution from @etiennestuder works for me. Get the code in [Kotlin DSL example](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/use_kotlin_dsl). Make sure you copy also folder _buildSrc_ with all the content. Folder _buildSrc_ should be placed in your project root

**Comment by etiennestuder** [comment]
As of 5.x, the gradle-jooq-plugin supports the Gradle Kotlin DSL as a first-class citizen. See the README file:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md

See this complete example written with the Gradle Kotlin DSL:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts
