### ISSUE TITLE
TINYINT to Boolean forced type conversion is problematic

### ISSUE THREAD

**Issue by betterclever** [etiennestuder/gradle-jooq-plugin#123]
I am using a configuration like below but the TINYINT(1) type is still being generated as Byte and not Boolean, can someone tell what's wrong in the configuration?

```
database {
     name = 'org.jooq.meta.mysql.MySQLDatabase'
    inputSchema = 'example'
    forcedTypes {
        forcedType {
            name = "BOOLEAN"
            types = "(?i:(TINY|SMALL|MEDIUM|BIG)?INT(UNSIGNED)?\\(1\\))"
        }
    }
}
```

Plugin Version: 3.0.3
Jooq Version: 3.12.3

Reference: https://blog.jooq.org/2019/09/27/how-to-map-mysqls-tinyint1-to-boolean-in-jooq/

**Comment by etiennestuder** [comment]
I suggest you use the [latest plugin version](https://github.com/etiennestuder/gradle-jooq-plugin/releases), check if the problem still persists in the genrated code, and if so, contact @lukaseder from jOOQ.

**Comment by betterclever** [comment]
I did not realize that the version I was using doesn't use Jooq 3.12 XSD to generate.
I could not upgrade to latest plugin due to Gradle being 4.x and hard dependencies making to hard to migrate.
I used the approach here to generate: https://www.jooq.org/doc/3.13/manual/code-generation/codegen-gradle/#N6A6DE

Thanks for the help btw.
