### ISSUE TITLE
A configuration normalization hook is provided to increase up to date cache hit rate

### ISSUE THREAD

**Issue by jonnybbb** [etiennestuder/gradle-jooq-plugin#124]
Currently the up to date check of the `generateSchema` task is based on the defined jooq configuration in the buildscript. Any change of the configuration will result in a negative up to date check.  In a scenario where the database is created from sql scripts and the jdbc configuration differs for example on a local machine vs CI server - the local machine cannot benefit from the generated cache artifacts of the CI server. To overcome this limitation a normalization hook should be provided in the DSL to override any configuration property, so that the cache key generation can be made less volatile.

**Comment by etiennestuder** [comment]
Available on master via https://github.com/etiennestuder/gradle-jooq-plugin/commit/9abd253da6d650215d9e8cedf56ffe8b18d34398
