### ISSUE TITLE
Can an xml config file be used?

### ISSUE THREAD

**Issue by benmccann** [etiennestuder/gradle-jooq-plugin#128]
Hi, thanks for providing this plugin! I have a `jooq-codegen.xml` file from an existing project which is similar to the one shown here: https://www.jooq.org/doc/latest/manual/code-generation/codegen-configuration/

Is it possible for me to use this xml file or do I have to move the configuration from the xml file into the build file?

**Comment by etiennestuder** [comment]
@benmccann You need to move to the in-build configuration that my plugin offers/needs, or you can take a look at some of the other jooq plugins that operate directly on the jooq xml config file.
