### ISSUE TITLE
Provide example for Kotlin DSL

### ISSUE THREAD

**Issue by axelfontaine** [etiennestuder/gradle-jooq-plugin#131]
Currently only the Groovy DSL is documented. It would be great to have examples also available for the Kotlin DSL as dealing with things like configuration names is a bit different than with Groovy.

**Comment by etiennestuder** [comment]
Please read the README. Samples are listed here:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#samples

**Comment by etiennestuder** [comment]
As of 5.x, the gradle-jooq-plugin supports the Gradle Kotlin DSL as a first-class citizen. See the README file:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md

See this complete example written with the Gradle Kotlin DSL:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts
