### ISSUE TITLE
How to configure the log level of a task

### ISSUE THREAD

**Issue by psysp** [etiennestuder/gradle-jooq-plugin#133]
Can the logging of the code generation be some controlled by the plugin?

When the task is running that logs get filled with a ton of log message from org.jooq.tools.LoggerListener and org.jooq.meta.DefaultRelations.

**Comment by etiennestuder** [comment]
Did you check the jooq config for setting the log level?

```
jooq {
    sample(sourceSets.main) {
        logging = org.jooq.meta.jaxb.Logging.WARN
        ...
     }
}
```
