### ISSUE TITLE
Error message for jooqRuntime configuration in 5.0

### ISSUE THREAD

**Issue by adamkobor** [etiennestuder/gradle-jooq-plugin#134]
Hi, 

first of all: thanks for your hard work with this plugin 🙏 

I'm facing an issue with version 5.0 (Gradle version: 6.6), jooqRuntime configuration seems to be broken:

```
> Could not find method jooqRuntime() for arguments [org.postgresql:postgresql:42.2.14] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Did I miss something? I didn't make any change when upgraded from 4.2 to 5.0, and the same setup worked like a charm in 4.2

**Comment by etiennestuder** [comment]
@adamkobor the DSL has changed. I'm still in the process of updating the documentation. For the time being, please take a look at this example: https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_groovy_dsl/build.gradle

**Comment by adamkobor** [comment]
Hey @etiennestuder, thanks for your quick response, it works 👍

**Comment by etiennestuder** [comment]
Great. Thanks for letting me know.
