### ISSUE TITLE
doc(spring-boot): using dependencyManagement to set the version possible?

### ISSUE THREAD

**Issue by davinkevin** [etiennestuder/gradle-jooq-plugin#137]
Hi, 

This is more a question than an issue, but I think this could lead to an improvment in the documentation or in the code…

I've set the following, in a spring-boot project: 

```
jooq {
	version.set( dependencyManagement.importedProperties["jooq.version"] )
	edition.set(OSS)
}
```

I use the version defined by Spring, like documented here: https://docs.spring.io/dependency-management-plugin/docs/current-SNAPSHOT/reference/html/#accessing-properties

Thanks to that, I think I can keep the jooq version in the plugin and in spring boot in sync.

Do you think this is a valid solution? If yes, we could add it to the documentation / add to an example (I can do the PR if required, let me know).

BTW, thanks for the last release of the plugin with the Kotlin DSL support, I'm very glad to use it with ease in gradle context ❤️.

**Comment by etiennestuder** [comment]
@davinkevin Thanks for the input. Your proposal seems good to me. Having an example build for this and a reference to the build from the Examples section of the README would be great. Getting a PR for this would be lovely.

Note that I have this paragraph, but it explains it for the opposite usee case:
https://github.com/etiennestuder/gradle-jooq-plugin#explicitly-setting-the-jooq-version-property-expected-by-the-spring-boot-plugin

**Comment by etiennestuder** [comment]
@davinkevin I extended this [paragraph](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#synchronizing-the-jooq-version-between-the-spring-boot-gradle-plugin-and-the-jooq-gradle-plugin). If you have further suggestions or improvements, please reopen the issue.

**Comment by davinkevin** [comment]
I've opened the [PR](https://github.com/etiennestuder/gradle-jooq-plugin/pull/139) about the example. I usually do PR during weekend, but you change the documentation before I can propose something 😉. 

Thank you again for the plugin and answer.

**Comment by etiennestuder** [comment]
Cool. I'll take a look this week-end. Thanks in advance.

**Comment by etiennestuder** [comment]
@davinkevin Thanks very much. This is now on master.
