### ISSUE TITLE
Testcontainer but initiation function causing ClassNotFoundException

### ISSUE THREAD

**Issue by lucasm0ta** [etiennestuder/gradle-jooq-plugin#140]
I'm trying to setup a testcontainer which would make it easier to generate jOOQ schemas. But as I try to use a init funtion for the migration process, this function cannot be found raising the error: 
```
java.sql.SQLException: Error while executing init function: com.sample.Clazz::staticFunc
        at org.testcontainers.jdbc.ContainerDatabaseDriver.runInitFunctionIfRequired(ContainerDatabaseDriver.java:226)
        at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:133)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:354)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:222)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:217)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:189)
Caused by: java.lang.ClassNotFoundException: com.sample.Clazz
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.testcontainers.jdbc.ContainerDatabaseDriver.runInitFunctionIfRequired(ContainerDatabaseDriver.java:220)
        ... 5 more
```
I'm using the jooq plugin as the following configuration:
```
apply plugin: 'nu.studer.jooq'

dependencies {
    jooqGenerator("org.slf4j:slf4j-simple:1.7.30")
    jooqGenerator("org.jooq:jooq:3.13.4")
    jooqGenerator("org.jooq:jooq-meta-extensions:3.13.4")
    jooqGenerator('org.testcontainers:testcontainers:1.14.3')
    jooqGenerator('org.testcontainers:postgresql:1.14.3')
    jooqGenerator("org.postgresql:postgresql:42.2.6")
}

jooq {
    version = '3.13.4'
    configurations {
        main {
            generateSchemaSourceOnCompilation = false
            generationTool {
                logging = 'TRACE'
                jdbc {
                    driver = 'org.testcontainers.jdbc.ContainerDatabaseDriver'
                    url = 'jdbc:tc:postgresql:10.7:///dbname?TC_INITFUNCTION=com.sample.Clazz::staticFunc'
                }
                generator {
                ...
                }
            }
        }
    }
}
```
I was wondering if this was a problem within the testcontainer, but setting the testcointainer as the data source from a spring application works correctly.
Also, I tried:

* To use the main funtion as entrypoint and it gave the same which made me question the classes were not even available.
* Set the `generateJooq` task depending on the `compileJava` expecting it would make the class available.

Looking internally, the function call `Class.forName("com.sample.Clazz")` raises the exception. Any idea why it is not accesible when using through jOOQ plugin ?

**Comment by etiennestuder** [comment]
The only classes available on the classpath when running the jooq code generator are those that you add specifically to the `jooqGenerator` configuration. In your code snippet above, you are only adding the third-party dependencies.

You can also see the full classpath passed to the `jooqGenerate` task by running the Gradle build with `-i`. Make sure that your com.sample.Clazz is also properly added to that classpath. That's as far as I can help here.

**Comment by lucasm0ta** [comment]
After suffering more than I wished for, I managed to make this migrator class into a separate module and just used the following:
```
dependencies {
    jooqGenerator project(':config') // submodule

    jooqGenerator("org.slf4j:slf4j-simple:1.7.30")
    ...
```
Not the most beautiful solution, but worked like a charm :)

Thanks @etiennestuder for the input

---

For posterity, this custom migrator uses Flyway, which has no given support for single sql connection. After going around, [found a that jooq has a wrapper](https://stackoverflow.com/questions/7147397/use-java-sql-connection-as-datasource-for-flyway#comment8587566_7155984) which enables to create a DataSource that Flyway receives as a configuration input.

```
import org.flywaydb.core.Flyway;
import org.jooq.tools.jdbc.SingleConnectionDataSource;

import java.sql.Connection;
import java.sql.SQLException;

public class ContainerMigrator {
    public static void migrate(Connection connection) throws SQLException {
        SingleConnectionDataSource sdf = new SingleConnectionDataSource(connection);
        Flyway flyway = Flyway.configure().dataSource(sdf).load();
        flyway.migrate();
    }
}
```

**Comment by etiennestuder** [comment]
Glad you got it working. 

> After suffering more than I wished for,...

Did you take a look at the [Examples](https://github.com/etiennestuder/gradle-jooq-plugin#examples) before you started debugging? There is an example on[ how to use a custom generator strategy defined in the same Gradle multi-module project](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_custom_generator_strategy/build.gradle). Not exactly the same requirement, but conceptually very similar.

> Not the most beautiful solution, but worked like a charm :)

This is a very good solution, IMO. It's a nice modularity that will also maximize task avoidance when the only thing that changes is code realted to `com.sample.Clazz`.

**Comment by JayAhn2** [comment]
@lucasm0ta Could you let use have the full example for jooq + testcontainers + flyway? I cannot follow the codes in this thread. thanks!

**Comment by JayAhn2** [comment]
I found a nice example for this exact case.
https://github.com/swaechter/jooq-gradle-testcontainer-flyway-example
