### ISSUE TITLE
Changing package name leaves orphaned files from previous package

### ISSUE THREAD

**Issue by ldaley** [etiennestuder/gradle-jooq-plugin#141]
The task is not removing old files before generation. When the package name of generated classes changes, the generated classes in the old package are not removed on the next run. 

A solution would be to clean the output directory before invoking the generator.

**Comment by etiennestuder** [comment]
I thought Gradle is doing this?

**Comment by ldaley** [comment]
Gradle will only ensure that the directory has been created if it doesn't already exist.

**Comment by etiennestuder** [comment]
Fixed via https://github.com/etiennestuder/gradle-jooq-plugin/commit/08b2eb36a5ed308a0bf9ce78deeb57eb8f1cd833

**Comment by etiennestuder** [comment]
Thanks for reporting it, @ldaley .

**Comment by etiennestuder** [comment]
Released in version 5.0.3.
