### ISSUE TITLE
Example links lead to source page

### ISSUE THREAD

**Issue by iceback** [etiennestuder/gradle-jooq-plugin#145]
Are the Example links performing as intended?  Form the Examples page [EG](https://github.com/etiennestuder/gradle-jooq-plugin#examples) I choose the Customize execution [link](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_generation_tool_execution) and there I'm at the root of the project with just the basic gradle files and the Wiki link leads back the general documentation.  Somewhat circular.

I'm having trouble getting my custom generator class on the classpath.  It's in a sibling project and my jooq project depends on that sibling.  This was sufficient before moving to V5, but I had to use this in my jooq project to get postgres to the generation step
`dependencies {
  jooqGenerator project (':anno')
  jooqGenerator "org.postgresql:postgresql:42.2.+"
}
`
The "anno" project has my custom generator but still I get ClassNotFound in reference to my custom generator.

I see in one of the checkins
`tasks.named('generateJooq').configure {
    // customize execution of the code generation tool (only show output if code generation failed)`

Is this a place for addressing the classpath of the generation step?

**Comment by iceback** [comment]
I found my error, nothing to do with the plugin of course.  However, I'll leave this open as the question of the links is, in my mind, still valid.

**Comment by etiennestuder** [comment]
I don't understand the issue with the linking. If you click on the [https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/configure_generation_tool_execution](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/configure_generation_tool_execution) link, it takes you to a self-contained, complete Gradle project that demonstrates the given feature.

**Comment by iceback** [comment]
Sorry, it wasn't obvious to me that I needed to open the build.gradle per example.  I was expecting the information to be under the wiki link.  Perhaps the "example" link could just open the corresponding build.gradle?

**Comment by etiennestuder** [comment]
No worries. I do not point to the build file since for some examples, it is not just the build file but other files/folder that are relevant for the example.
