### ISSUE TITLE
Cannot bind multiple configurations to main

### ISSUE THREAD

**Issue by ayush-finix** [etiennestuder/gradle-jooq-plugin#146]
We've recently tried to upgrade to 5.1.1 from 3.x and are having trouble with a certain setup. We used to use a single jooq block to generate multiple different views of our db targeting the same source set. Example below stripped for clarity (left a little to give the idea of the use case)
```
jooq {

target1(sourceSets.main) {
        logging = 'ERROR'
        jdbc {
            ...
        }
        generator {
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                includes = '.*'
                excludes = ''
                schemata {
                    schema {
                        inputSchema = 'schema1'
                    }
                }
            }
            generate {
                ...
            }
            target {
                packageName = 'target1.jooq'
                directory = "${buildDir}/generated-sources/jooq"
            }
        }
    }

target2(sourceSets.main) {
        logging = 'ERROR'
        jdbc {
            driver = 'org.postgresql.Driver'
        }
        generator {
            name = 'customGenerator'
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                includeExcludeColumns = true
                schemata {
                    schema {
                        inputSchema = 'schema2'
                    }
                    schema {
                        inputSchema = 'schema3'
                    }
                }
                forcedTypes {
                   ...
                 }

            }
            strategy {
                name = 'customStrategy'
            }
            generate {
                ...
            }
            target {
                packageName = 'target2.jooq'
                directory = "${buildDir}/generated-sources/jooq"
            }
        }
    }
}
```
The output of above would be a structure like this
```
build/generated-sources/jooq/<packageStructureTarget1>
build/generated-sources/jooq/<packageStructureTarget2>
```
where the `build/generated-sources/jooq` folder was bound to the main source set and the various "configurations" under the plugin generated into their own directory/package structure under it.

I'm not quite sure how to port this over to the new plugin syntax.

I've tried using multiple main
```
configurations {
    main {packageName = <1>, directory="${buildDir}/generated-sources/jooq/target1"}
    main {packageName = <2>, directory="${buildDir}/generated-sources/jooq/target2"}
}
```
but this just appears to have the last one win (even with different directories targeted) and is probably a personal misunderstanding of the the dsl syntax.

I've tried using different names
```
configurations {
     1 {packageName = <1>, directory="${buildDir}/generated-sources/jooq"}
     2 {packageName = <2>, directory="${buildDir}/generated-sources/jooq"}
}
```
and I ran into an issue where it seems the jooq tasks really want their own output directories, so changed to
```
configurations {
     1 {packageName = <1>, directory="${buildDir}/generated-sources/jooq/target1"}
     2 {packageName = <2>, directory="${buildDir}/generated-sources/jooq/target2"}
}
```
but I'm not sure how to get the source sets to work under the main compile tasks without adding them. I can get the task dependency to work by doing something like `compileJava.dependsOn(tasks.withType(nu.studer.gradle.jooq.JooqGenerate))`, but I don't know a way to get the sourceSets added to main. This also feels like I'm ballooning the gradle configurations for no real value compared to the 3.x style.

Is there any way to target the same source set but create different tasks basically?

**Comment by etiennestuder** [comment]
@ayush-finix I'll try to get back to you over the week-end.

**Comment by etiennestuder** [comment]
@ayush-finix 

I've put together an [example](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_different_jooq_sources_for_same_target_source_set/build.gradle) that does what you are asking for. The task wiring happens implicitly and still keeps up task configuration avoidance. 

You can also see in this [build scan](https://scans.gradle.com/s/wy3zsn5wt2s7g/timeline) how the two jOOQ configurations are executed before Java compilation takes place.

**Comment by ayush-finix** [comment]
I think it can be simplified to 
```
sourceSets.main.java.srcDirs(
    tasks.withType(JooqGenerate)*.outputDir
)
```
while still avoiding task configuration: https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_pitfalls.

**Comment by etiennestuder** [comment]
> while still avoiding task configuration:

Nope:
- [build scan](https://scans.gradle.com/s/kdsdiajjzawb4/performance/configuration#summary-tasks-created-during-configuration) with your suggestion and early configuration
- [build scan](https://scans.gradle.com/s/mdthu55srfwoe/performance/configuration?openScriptsAndPlugins=WzBd#summary-tasks-created-during-task-graph-calculation) with my code and lazy configuration

**Comment by ayush-finix** [comment]
I opened a ticket for gradle: https://github.com/gradle/gradle/issues/14870
and I got a surprising suggestion:
```
sourceSets.main.java.srcDirs(
    tasks.withType(JooqGenerate)
)
```
I ran the scan and it appears identical to the individually named ones: https://scans.gradle.com/s/xl5a2ae4w2mrm/performance/configuration
