### ISSUE TITLE
Multiple configurations targeting the same output directory causes a race condition

### ISSUE THREAD

**Issue by ayush-finix** [etiennestuder/gradle-jooq-plugin#147]
The example: https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_different_jooq_sources_for_same_target_source_set/build.gradle, won't actually have two different generation sets. I believe the directory is wiped by the two different task invocations.
I believe you'd have to do something like (changes with **)

```
...
target {
    packageName = 'nu.studer.sample.first'
    **directory = 'output/first'**
}
...
target {
    packageName = 'nu.studer.sample.first'
    **directory = 'output/second'**
}
...
```
To actually have it generate correctly.

**Comment by etiennestuder** [comment]
Nope. If you read my example closely, you can see that I specify different packages for the two generation sets. And regardless of that, each jOOQ configuration is by default generated into a seperate directory that contains the directory name.

Please don't create issues based on speculation.

**Comment by ayush-finix** [comment]
Apologies. I realize our project had each of the outputs configured as 
```
<first>
directory = "${buildDir}/generated-sources/jooq"

<second>
directory = "${buildDir}/generated-sources/jooq"
```
which used to work with the older version of the plugin. So it's only a problem if you pick the same directory manually.

**Comment by etiennestuder** [comment]
No worries @ayush-finix. Yes, each task cleans the output directory before generating the sources into it. This was done in [5.0.3](https://github.com/etiennestuder/gradle-jooq-plugin/releases/tag/v5.0.3). There is a request to have a flag for this.
