### ISSUE TITLE
Make deletion of content in output directory optional

### ISSUE THREAD

**Issue by mzhafez** [etiennestuder/gradle-jooq-plugin#148]
Is it possible to make deletion of content in output directory optional (through setting the "clean" flag)?

**Comment by etiennestuder** [comment]
No. Deletion is done to ensure no stale outputs are lurking around from a previous run.

**Comment by mzhafez** [comment]
Looking at official jooq documentation: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-target/

Not really getting the purpose of the "clean" flag there. Isn't its sole purpose not to delete the content of the output directory?

**Comment by lukaseder** [comment]
Here's the feature request: https://github.com/jOOQ/jOOQ/issues/6140

> The 'problem' ist that jOOQ is doing things it should not do, but instead defer to the caller.

The world is messier than you think, and jOOQ is less opinionated than you like 😉

**Comment by etiennestuder** [comment]
`We should make that optional, in case users decide to put hand-written files in those directories.`

--> when triggering jOOQ via Gradle once should not do this since it leads to overlapping outputs. There much better ways to achieve this with Gradle. Thus, having a delete flag in when triggering jOOQ via Gradle jOOQ task is a way to shoot yourself in the foot, which I don't want to happen.

**Comment by lukaseder** [comment]
Sure, I understand. But "triggering jOOQ via Gradle" is one of many options. Believe it or not, but many people like to run the code generator as a standalone tool in their IDE. In that case, there may be valid reasons why people would want this flag.

I understand that you don't want to support it. How about ignoring it from Gradle configurations, and if someone sets it, log a warning pointing to this issue?

**Comment by etiennestuder** [comment]
@lukaseder Understood. I will look into it soon.

**Comment by etiennestuder** [comment]
After some internal discussions with our build cache experts, we have decided that as of version 5.2 of the gradle-jooq-plugin, the JooqGenerate task fails with a message explaining that it is unsafe to not clear the output directory.
