### ISSUE TITLE
Nested types

### ISSUE THREAD

**Issue by jensenbox** [etiennestuder/gradle-jooq-plugin#15]
I am having a super hard time finding the right gradle syntax to represent the XML found at: http://www.jooq.org/doc/3.8/manual-single-page/#custom-data-types

Specifically the customTypes with the customType.

Here is what I have that is totally not working:

```
             database {
                name = 'org.jooq.util.postgres.PostgresDatabase'
                inputSchema = 'public'

                customTypes = [
                        customType {
                            name = 'JsonElement'
                            type = 'com.google.gson.JsonElement'
                            binding = 'com.closient.jooq.util.PostgresJSONGsonBinding'
                        }
                ]

                forcedTypes = [
                    forcedType {
                        name = 'JsonElement'
                        expression = '.*JSON.*'
                        types = '.*'
                    }
                ]

            }
```

**Comment by bosakm** [comment]
Try something like:
customTypes {
     customType {
	name = 'JsonElement'
        type = 'com.google.gson.JsonElement'
        binding = 'com.closient.jooq.util.PostgresJSONGsonBinding'
      }
}

**Comment by oehme** [comment]
As @bosakm showed, the syntax is actually very regular, so I see no need to change here.

**Comment by etiennestuder** [comment]
See explanation given by @bosakm on how this can be achieved.
