### ISSUE TITLE
jooq dependency update

### ISSUE THREAD

**Issue by Horstexplorer** [etiennestuder/gradle-jooq-plugin#150]
it seems like using the plugin (5.2) forces gradle to include the jooq dependencies v3.13.5 even if newer ones (v3.14.1) are specified. it would be nice if this could be updated so we could take advantage of the bug fixes in this version more easily.

**Comment by etiennestuder** [comment]
RTFM:
- https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#specifying-the-jooq-version-and-edition
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#enforcing-the-jooq-configuration-xml-schema-version
