### ISSUE TITLE
3.14.1 availibility ?

### ISSUE THREAD

**Issue by JayChandler** [etiennestuder/gradle-jooq-plugin#153]
When will there be a release for 3.14.1?

Thx

**Comment by lukaseder** [comment]
Note the current release is 3.14.3... (on Maven Central, shortly)

**Comment by etiennestuder** [comment]
There is no need for a new gradle-jooq-plugin release just to use a new version of jOOQ. Please check the docs:

See
- https://github.com/etiennestuder/gradle-jooq-plugin#specifying-the-jooq-version-and-edition
- https://github.com/etiennestuder/gradle-jooq-plugin#enforcing-the-jooq-configuration-xml-schema-version

**Comment by xeoneux** [comment]
Thanks @etiennestuder for the plugin, finally got it working :+1: 
As a newbie to Gradle, it took me more than an hour to figure this out :smile: 
Explaining this particular issue in a bit more verbose manner would really help!
