### ISSUE TITLE
All contents of target.directory are removed

### ISSUE THREAD

**Issue by mtakuma** [etiennestuder/gradle-jooq-plugin#155]
I share my main source code directory (e.g. `src/main/java`) to place both my main code and jooq generated code.  I expect the plugin to remove contents under the `target.packageName` directory but it seems to remove all contents in `target.directory`?

**Comment by etiennestuder** [comment]
That's correct. I've explained this repeatedly on other GH issues that were raised. Please check them out.
See also [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#generating-sources-into-shared-folders-eg-srcmainjava) from the docs.

**Comment by mtakuma** [comment]
Thank you for your prompt reply!  My configuration did work as expected with version 5.0.2 so I think the behavior is changed.

The pointed document _recommends_ distinct output directory, but how can I configure the plugin to use shared source directory?

**Comment by etiennestuder** [comment]
> Thank you for your prompt reply! My configuration did work as expected with version 5.0.2 so I think the behavior is changed.

Yes. See https://github.com/etiennestuder/gradle-jooq-plugin/releases/tag/v5.0.3

> The pointed document _recommends_ distinct output directory, but how can I configure the plugin to use shared source directory? 

Do not share directories, but use a separate downstream task to copy over the generated jOOQ sources to where you want them to be.

**Comment by mtakuma** [comment]
Thank you again for your suggestion to copy the generated sources.
Let me ask one more question if you have time to volunteer.

My solution so far, for minimum change to gradle definition, is
1. Place a fresh directory in my project and let the plugin generate into the directory `target { directory = 'src/myjooq/java' }`
1. Add the directory to main source set `sourceSets.main.java.srcDirs += ['src/myjooq/java']`

Do you see any pros/cons compared to your suggested approach?

**Comment by etiennestuder** [comment]
This is the approach I would suggest by default :-) It's also what the jooq plugin does out of the box if you name the jOOQ configuration `main` and explicitly specify the target directory as `src/myjooq/java`. See also [this example](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_groovy_dsl/build.gradle#L61).
