### ISSUE TITLE
Can't use KotlinGenerator

### ISSUE THREAD

**Issue by Ryuuji159** [etiennestuder/gradle-jooq-plugin#160]
Im trying to use this plugin to do the generation on a Kotlin project using Gradle with Kotlin DSL, but the generation fails if I use the KotlinGenerator class, this is the abridged `build.gradle.kts`:
```
dependencies {
    testImplementation(kotlin("test-testng"))

    implementation("org.jooq:jooq:3.14.4")
    implementation("org.jooq:jooq-meta:3.14.4")
    implementation("org.mariadb.jdbc:mariadb-java-client:2.7.1")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.4.30-M1")
    implementation("org.jooq:jooq-kotlin:3.14.4")

    jooqGenerator("org.mariadb.jdbc:mariadb-java-client:2.7.1")
    jooqGenerator("org.jooq:jooq-kotlin:3.14.4")
}

jooq {
    configurations {
        create("main") {
            jooqConfiguration.apply {
                jdbc.apply {
                    driver = "org.mariadb.jdbc.Driver"
                    url = "jdbc:mariadb://localhost:3306/db"
                    user = "root"
                    password = ""
                    properties.add(Property().withKey("PAGE_SIZE").withValue("2048"))
                }
                generator.apply {
                    name = "org.jooq.codegen.KotlinGenerator"
                    database.apply {
                        name = "org.jooq.meta.mariadb.MariaDBDatabase"
                        inputSchema = "db"
                    }
                    target.apply {
                        packageName = "jooq"
                        directory = "src/main/generated"
                    }
                }
            }
        }
    }
}
```

The error says that is trying to download the `org.jooq.jooq-kotlin` version 3.13.5 even though I'm asking for version 3.14.4

```
Execution failed for task ':generateJooq'.
> Could not resolve all files for configuration ':jooqGenerator'.
   > Could not find org.jooq:jooq-kotlin:3.13.5.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jooq/jooq-kotlin/3.13.5/jooq-kotlin-3.13.5.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I imagine it has something to do with this plugin because if I dont declare the `jooq-kotlin` dependency it simply fails because it cant find the KotlinGenerator class

```
SEVERE: Cannot read C:\Users\Ryuuji\src\kotlin\build\tmp\generateJooq\config.xml. Error : org.jooq.codegen.KotlinGenerator
java.lang.ClassNotFoundException: org.jooq.codegen.KotlinGenerator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.jooq.codegen.GenerationTool.loadClass0(GenerationTool.java:986)
	at org.jooq.codegen.GenerationTool.loadClass(GenerationTool.java:930)
	at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:364)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:225)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:192)
```

**Comment by etiennestuder** [comment]
You need to define the jOOQ version to use via the jooq plugin DSL. See
- https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#specifying-the-jooq-version-and-edition
- https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#enforcing-the-jooq-configuration-xml-schema-version

**Comment by Ryuuji159** [comment]
I didn't think I needed to declare the version, sorry.
But with just that I also needed to add the specific version of org.jooq.joor since is the only one that doesnt follows the same versioning.

```
buildscript {
    configurations["classpath"].resolutionStrategy.eachDependency {
        if (requested.group == "org.jooq") {
            if (requested.name == "joor") useVersion("0.9.13")
            else useVersion("3.14.4")
        }
    }
}
```

With that is working but with the `An illegal reflective access operation has occurred` warning, I imagine that's on jOOQ itself.
Thanks for your time

**Comment by etiennestuder** [comment]
I believe you could achieve what you want by:

1. Remove the dependency declaration of `org.jooq:jooq` since it is added by the gradle jooq plugin automatically
1. Remove the depencency declaration of `org.jooq:jooq-meta` since it is typically not needed to compile or run your code
1. Possibly also remove the dependency declaration of `org.jooq:jooq-kotlin` from the `implementation` configuration since it is probably only needed while jooq runs the source generator (keep it for the `jooqGenerator` configuration)
1. Set the jooq version in the gradle jooq plugin DSL via `jooq {  version.set("3.14.4") ... }`
1. Do not add a resolution startegy via `buildscript { configurations["classpath"].resolutionStrategy ... } but instead add a resolution strategy via:
```
configurations["jooqGenerator"].resolutionStrategy.eachDependency {
    if (requested.group == "org.jooq") && requested.name == "joor") { useVersion("0.9.13") }
}
```

**Comment by etiennestuder** [comment]
Hint: if you run the Gradle build with `--scan`, you will get a visual representation of the entire resolved dependency graph (and much more) on [scans.gradle.com](https://scans.gradle.com), including detailed information what dependencies were resolved, why they were resolved, and in what version.

**Comment by xenomachina** [comment]
I'm using [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin) and [gradle-use-latest-versions-plugin](https://github.com/patrikerdes/gradle-use-latest-versions-plugin). Strangely, they always see whatever jooq version gradle-jooq-plugin is using as being the "latest" version, even if there's a later version of jooq available.

This means that if I *don't* specify a version in the `jooq { ... }` block, then gradle-jooq-plugin is updated to its latest version, and jooq is updated to the version gradle-jooq-plugin defaults to. So jooq eventually gets updated, but on the same schedule as gradle-jooq-plugin's default.

However, if I *do* specify a version in the `jooq { ... }` block then gradle-jooq-plugin still get updated to its latest version, but jooq **never** gets upgraded. There ends up being a sort of feedback loop where whatever version jooq is already set to gets stuck as the "latest" version of jooq as far as gradle-versions-plugin and gradle-use-latest-versions-plugin are concerned.

I don't know the internals of gradle or these plugins that well, but my understanding is that gradle-use-latest-versions-plugin just uses gradle-versions-plugin, and gradle-versions-plugin in turn somehow leverages off of gradle's built-in "+" version resolution.

Do you have any ideas of how I might be able to break that feedback loop, and have gradle-use-latest-versions-plugin bump jooq to its *actual* latest version, and in turn have gradle-jooq-plugin use that same version of jooq?

**Comment by etiennestuder** [comment]
@xenomachina I'm not familiar with the gradle-versions-plugin and gradle-use-latest-versions-plugin, thus I'm sorry I cannot give you and valuabel advice.
