### ISSUE TITLE
Using "org.jooq:jooq:+" with gradle-jooq-plugin doesn't get latest version of jooq

### ISSUE THREAD

**Issue by xenomachina** [etiennestuder/gradle-jooq-plugin#162]
As a follow-up to the issue I mentioned in #160, here's how to reproduce the problem without using any other plugins.

## Steps to reproduce:

First, create a project with the following `build.gradle`:

``` groovy
buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'nu.studer.jooq' version '5.2'
}
apply plugin: 'java-library'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jooq:jooq:+"
    jooqGenerator "org.postgresql:postgresql:42.2.18"
}

jooq {
    version.set("3.12.0")
}
```

Run `./gradlew dependencies | grep jooq`. The jooq version will be **3.12.0**.

Comment out `version.set("3.12.0")` in `build.gradle`, and run `./gradlew dependencies | grep jooq` again. The jooq version will be **3.13.5**.

Comment out all traces of gradle-jooq-plugin in `build.gradle`, and run `./gradlew dependencies | grep jooq` once more. The jooq version will be the current version of jooq (**3.14.4**, as I write this).

## Actual behavior:

It appears that something that gradle-jooq-plugin is doing is causing `"org.jooq:jooq:+"` to resolve to the version of jooq that 
gradle-jooq-plugin is using.

## Desired behavior:

`"org.jooq:jooq:+"` should refer to the latest version of jooq.

## More Info

I was able to reproduce this with Gradle versions 6.1.1 and 6.8.

I know that using "+" as a version is discouraged. I don't do this in my real code, but instead use  [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin) and [gradle-use-latest-versions-plugin](https://github.com/patrikerdes/gradle-use-latest-versions-plugin) to let me pin my versions (reproducible builds) but also easily bump my dependencies to the latest versions (less busy work).

**Comment by xenomachina** [comment]
I tried replacing `"org.jooq:jooq:+"` with `"org.jooq:jooq:latest.release"`, and get the exact same behavior. Instead of resolving to the latest release, it resolves to the version that gradle-versions-plugin is requesting.

**Comment by xenomachina** [comment]
I tried replacing `version.set("3.12.0")` with `version.set("latest.release")` (and also `version.set("+")`, for the sake of completeness), and changing the jooq dependency to use a pinned version. ie:

``` groovy
...
dependencies {
    implementation "org.jooq:jooq:3.13.5"
    jooqGenerator "org.postgresql:postgresql:42.2.18"
}

jooq {
    version.set("latest.release")
}
```

Running `./gradlew dependencies | grep jooq` prints:

```
--- org.jooq:jooq:3.13.5 -> 3.14.4
\--- org.jooq:jooq:3.13.5 (n)
jooqGenerator - The classpath used to invoke the jOOQ code generator. Add your JDBC driver, generator extensions, and additional dependencies here.
+--- org.jooq:jooq-codegen -> 3.14.4
|    +--- org.jooq:jooq:3.14.4
|    \--- org.jooq:jooq-meta:3.14.4
|         \--- org.jooq:jooq:3.14.4 (*)
\--- org.jooq:jooq:3.13.5 -> 3.14.4
\--- org.jooq:jooq:3.13.5 -> 3.14.4
\--- org.jooq:jooq:3.13.5 -> 3.14.4
```

So it looks like this is not a usable workaround, as I need to be able to have the jooq version pinned to a specific version (and actually get that version) for repeatable builds, but I need `"org.jooq:jooq:latest.release"` to be able to resolve to the actual latest release, so that I can do automatic upgrades.

**Comment by pavelsilent** [comment]
Hello. We also have same behaviour.
I use 5.2 plugin version, and also use jooq-meta-extensions-hibernate for generate classes. On the maven repository store only 3.14+ versions of jooq-meta-extensions-hibernate library, but this plugin require 3.13.5. Thus I can't use plugin.
Please, release new version with supporting jook 3.14 + versions.

**Comment by xenomachina** [comment]
@pavelsilent I think your issue may be solved by using `version.set("3.14.4")`, as long as you're willing to explicitly pin to that version of jooq.

The reason this doesn't work for me is that I'm implicitly (via the other plugins mentioned above) relying on `latest.release` pointing at the latest version of jooq so that I can detect when new versions are released.

**Comment by etiennestuder** [comment]
> Run `./gradlew dependencies | grep jooq`. The jooq version will be **3.12.0**.
> 
> Comment out `version.set("3.12.0")` in `build.gradle`, and run `./gradlew dependencies | grep jooq` again. The jooq version will be **3.13.5**.
> 
> Comment out all traces of gradle-jooq-plugin in `build.gradle`, and run `./gradlew dependencies | grep jooq` once more. The jooq version will be the current version of jooq (**3.14.4**, as I write this).

Yes, This is currently the expected behavior. If you set a version in the jooq DSL, it is applied. If you do not set one, the default version defined within the jooq plugin is applied. If you do not use the jooq plugin, whatever version you define in the dependencies block will be used, incl. support for `+`.

It's because the jooq plugin registers a resolution strategy:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/src/main/groovy/nu/studer/gradle/jooq/JooqPlugin.java#L82

**Comment by etiennestuder** [comment]
@pavelsilent Please see this closed [issue](https://github.com/etiennestuder/gradle-jooq-plugin/issues/160). It explains how you can make your use case work.

**Comment by etiennestuder** [comment]
@xenomachina If you defined the version as `+` in the jOOQ Gradle DSL, it will pick up the latest version of all jOOQ dependencies. You cna try it out with [this example](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_groovy_dsl/build.gradle#L17).

**Comment by xenomachina** [comment]
@etiennestuder, Do you mean to do something like:

``` groovy
plugins {
    id 'nu.studer.jooq' version '5.2'
}
...
dependencies {
    implementation "org.jooq:jooq:3.12.0"
   ...
}
...
jooq {
    version = "+"
    ...
}
```

?

Unfortunately, this still does not do what is desired, because it breaks repeatable builds. It ends up using (at the time I write this) jooq 3.14.7, despite the fact that I've specified  3.12.0 as the version I want in my dependencies.

I need to be able to specify a specific version of jooq, and get the version specified (not some other version), so that I can have repeatable builds. However, I'd also like `useLatestVersions` to be able to determine the *actual* latest release version of all of my dependencies so it can upgrade them. It can (apparently) only do this if "latest.release" resolves to the true latest release.

Is there any way to disable gradle-jooq-plugin's resolution strategy?

**Comment by etiennestuder** [comment]
> I need to be able to specify a specific version of jooq, and get the version specified (not some other version), so that I can have repeatable builds. However, I'd also like useLatestVersions to be able to determine the actual latest release version of all of my dependencies so it can upgrade them. It can (apparently) only do this if "latest.release" resolves to the true latest release.

Remove the version (`3.12.0`) from `implementation "org.jooq:jooq:3.12.0"` and leave everything else as it is, controlling the version exclusively via `jooq.version = ...`

> Is there any way to disable gradle-jooq-plugin's resolution strategy?

No.

**Comment by xenomachina** [comment]
> Remove the version (`3.12.0`) from `implementation "org.jooq:jooq:3.12.0"` and leave everything else as it is, controlling the version exclusively via `jooq.version = ...`

That doesn't seem to work. If I have:

``` groovy
plugins {
    id 'nu.studer.jooq' version '5.2'
}
...
dependencies {
    implementation "org.jooq:jooq"
   ...
}
...
jooq {
    version = "3.12.0"
    ...
}
```

...then `useLatestVersions` will update the plugin version:

``` groovy
plugins {
    id 'nu.studer.jooq' version '5.2.1'
```

but it doesn't update jooq's version:

``` groovy
jooq {
    version = "3.12.0"
```

Based on its output...

```
The following dependencies are using the latest release version:
...
 - org.jooq:jooq:3.12.0
 - org.jooq:jooq-codegen:3.12.0

The following dependencies have later release versions:
...
 - nu.studer.jooq:nu.studer.jooq.gradle.plugin [5.2 -> 5.2.1]
```

... I think `useLatestVersions` is unable to see that any versions of jooq exist other than the one specified in `jooq.version`. It still thinks `3.12.0` is the latest release version.

**Comment by etiennestuder** [comment]
I don't know what `useLatestVersions` is and what it does. I'd be surprised if it understands the jOOQ DSL and knows where to update the version. Given the output you pasted, it seems `useLatestVersions` is unable to determine that there is a newer version of the jooq dependency available. I do not know the cause of that limitation.

Apologies, but I've reached the end of my knowledge of what I can help you with.

**Comment by xenomachina** [comment]
`useLatestVersions` is a task from the [Gradle Use Latest Versions Plugin](https://github.com/patrikerdes/gradle-use-latest-versions-plugin#gradle-use-latest-versions-plugin). Instead of having to manually update the versions of our dependencies, it will update them for us. It lets us track the latest version of dependencies much more closely, as we can mostly automate the process of upgrading, but unlike using `+` or `latest.release`, it lets us have repeatable builds.

Yes, I agree that even if it were able to figure out that there was a newer version of jooq, if probably wouldn't be able to update the plugin's DSL. I think it only knows how to update the dependencies and plugins constructs.

I found a workaround, though it isn't incredibly pretty:

1. Set `jooq.version` to the same value I use in the `dependencies`:

   ```
   dependencies {
       implementation "org.jooq:jooq:$jooq_version"
   ...
   jooq {
       version = jooq_version
   ```
   
   I have `jooq_version` set in `gradle.properties`, though I think `useLatestVersions` may also supprt using a `def`.

2. Conditionally apply the plugin based on a property. I believe this requires the legacy plugin syntax:

   ```
   buildscript {
       dependencies {
           classpath "nu.studer.jooq:nu.studer.jooq.gradle.plugin:5.2.1"
   ...
   if (!project.hasProperty('inUseLatestVersions')) {
       apply plugin: "nu.studer.jooq"
   }
   ```

3. Also wrap the same condition around `jooqGenerator` dependencies, and anything else that requires the plugin. (For the latter, wrapping it around pretty much everything outside of `buildscript`, `plugins`, and `dependencies` works.)

4. When running `useLatestVersions`, set that property:
   ```
   ./gradlew --refresh-dependencies useLatestVersions -PinUseLatestVersions
   ```

So `useLatestVersions` can do its thing without the plugin hiding other versions of jooq, and when I'm not running `useLatestVersions`, the plugin uses the same version of jooq that's been explicitly specified.
