### ISSUE TITLE
Move plugin away from JCenter

### ISSUE THREAD

**Issue by rbuehlma** [etiennestuder/gradle-jooq-plugin#168]
JCenter will shut down in 2022 but already after March 31 2021, it will not be possible to provide any updates through JCenter. This addon should therefore be released to e.g. Maven Central.

Additional information can be found here:
https://blog.gradle.org/jcenter-shutdown

**Comment by etiennestuder** [comment]
Thanks. I'm aware of it. But, I do not have time for the migration to the plugin portal right now. Until a new release is required, things are ok the way they are.

**Comment by dsvensson** [comment]
Another benefit of central is that it requires signed artifacts, which improves using gradle verification feature.

**Comment by etiennestuder** [comment]
5.2.2 is the first version published to the Gradle Plugin Portal.
