### ISSUE TITLE
Is there any way to provide a regular expression in the inputSchema field of database

### ISSUE THREAD

**Issue by ishanm** [etiennestuder/gradle-jooq-plugin#17]
Hey, sorry I wasn't sure where to ask questions regarding the plugin.

We're using postgres as our datastore, with > 500 schemas, so am guessing to use JOOQ I'd need separate models created for every schema? So was wondering if there's a way to provide a regular expression in the `inputSchema` field of generator > database in my gradle config?

Thanks for creating this awesome project :)

**Comment by ishanm** [comment]
Ah just realized I should use a mapping of schemas, so I can map all my schemas to the same model.

**Comment by lukaseder** [comment]
For the record, `inputSchema` doesn't take regular expressions, but the `includes` and `excludes settings do, e.g. `(schema_1|schema_2)\..*`

**Comment by ishanm** [comment]
Thanks for your reply. Makes sense. For some reason though when I was playing with the `includes` and `excludes` settings they weren't being used to filter the schemas themselves but rather the tables in the schemas? I might have been doing something wrong.

**Comment by lukaseder** [comment]
Yes, indeed. They filter tables in the schemas. In your case, you will still get 500 empty schemas, then - that would be quite annoying. I've created a feature request to improve this in jOOQ: https://github.com/jOOQ/jOOQ/issues/5472

**Comment by ishanm** [comment]
Awesome, thanks!
