### ISSUE TITLE
[Q] Configure jooq version with platform bom

### ISSUE THREAD

**Issue by bademux** [etiennestuder/gradle-jooq-plugin#172]
Hi,

Is it possible to configure ```jooq.version``` while using gradle native bom suport:
```implementation enforcedPlatform("org.springframework.boot:spring-boot-dependencies:$springBootVersion")```

Thanks for simple and powerful tool!

**Comment by chairbender** [comment]
fwiw, I also prefer to use Gradle's native bom support, so I worked around this by creating a new gradle module that contains only the jooqGenerator plugin / configuration / generated code (and the dependencyManagement plugin set up to use the spring boot BOM) and included that module as a dependency from my actual module. I don't know how well this works along with the "generate schema source on compilation" feature though, as I have that disabled.

I would prefer if this library supported this case more easily, as I don't think Gradle has plans to expose maven properties from BOMs. For example, I'd prefer to be able to do something like this:

```
  jooqGenerator platform("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
```

And have this plugin get the config from there.

**Comment by bademux** [comment]
@chairbender unfortunately I don't use any spring plugins.

**Comment by chairbender** [comment]
@bademux I was just using that as an example of what I wanted, I would want to be able to use a BOM to define the version to use - the fact that I use spring plugin for the BOM coordinates is irrelevant.

We actually ended up just not using the plugin at all, instead we directly use the jooq codegen library and have a gradle task set up to run some code that uses that library. Works a lot better for us because we can spin up a DB in docker via testcontainers and have jooq scan that DB.

**Comment by bademux** [comment]
@chairbender the same for another project, I found that plugin is way more comfortable in terms of deining grade configurations 
That way or another we need to sync versions.

**Comment by bademux** [comment]
reformulating the problem
@etiennestuder Is it possible to do something like that? 
```groovy
jooq { 
  version = project.configurations.compileClasspath.resolvedConfiguration.resolvedArtifacts.find({ it.moduleVersion.id.name == 'jooq' }).moduleVersion.id.version
}
```

**Comment by etiennestuder** [comment]
Thanks for the ideas. Unfortunately, I will not have the time to look into BOMs in more detail. It's not clear to me either what exactly the gradle-jooq-plugin would have to do.

The gradle-jooq-plugin 9.0 no longer registers any custom dependency resolution rules. Maybe that will simplify the problem.

I will close this issue. I hope for your understanding.
