### ISSUE TITLE
[BUG] Plugin cleans all output dir. I must clean outputDir/package.

### ISSUE THREAD

**Issue by bademux** [etiennestuder/gradle-jooq-plugin#174]
Hi,
I use "semi-automatic" setup: all sources are committed into git, so sources are regenerated manually on input data changed.
For all generated sources I have "generated" dir, so gradle-jooq-plugin removes all files there.
In my opinion gradle-jooq-plugin should remove only jooq package ```generator.target.packageName``` but not full dir.

Thanks

**Comment by bademux** [comment]
Yes, I'm aware of that. But due to some restriction it will be hard to do so.
While I think it is good default to warn user, the exception is not the best solution ```generator.target.clean = true```.

**Comment by etiennestuder** [comment]
> Yes, I'm aware of that. But due to some restriction it will be hard to do so.
Yeah, I can understand that.

> While I think it is good default to warn user, the exception is not the best solution generator.target.clean = true.
I chose it because it is better than a possibly corrupted Gradle build when the task does not exclusively own the output directory.
