### ISSUE TITLE
[Q] Is it possible to configure the jOOQ Plugin in a different gradle file?

### ISSUE THREAD

**Issue by p-** [etiennestuder/gradle-jooq-plugin#178]
Hello!
Firstly, thanks for your great plugin!

When I tried to configure the Gradle jOOQ plugin in a seperate gradle file it worked as long as I didn't use any classes from the jOOQ plugin, but as soon as I tried to set the log level or the edition by passing an enum from the class `JooqEdition` the generation failed with messages such as:

> Cannot cast object 'DEBUG' with class 'org.jooq.meta.jaxb.Logging' to class 'org.jooq.meta.jaxb.Logging'

So my question: Is it possible to configure the jOOQ plugin in a seperate gradle file or does anybody know what I'm doing wrong?

----
## Setup
Gradle Version: 6.7
jOOQ Gradle Plugin 5.2.2

Project Gradle File:
```groovy
plugins {
	[..]
	id 'nu.studer.jooq' version '5.2.2' apply false
}
[..]
apply from: 'gradle/jooq-support.gradle'
```

gradle/jooq-support.gradle
```groovy
buildscript {
	repositories {
		maven { url = uri("https://plugins.gradle.org/m2/") }
	}

	dependencies {
		classpath 'nu.studer:gradle-jooq-plugin:5.2.2'
	}
}

apply plugin: 'nu.studer.jooq'

[..]
jooq {
	version = "3.14.3"
	configurations {
		main {
			generationTool {
				logging = org.jooq.meta.jaxb.Logging.DEBUG
				generator {
[..]
```

jOOQ Generation in this project works as long as everything is configured directly in the project gradle file or as long as no classes from the jOOQ Plugin are in use (such as `JooqEdition`).

**Comment by etiennestuder** [comment]
@p- Thanks for the question.

I've added an example that I believe should cover what you are looking for:
https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/extract_script_file

Did you consider this approach?
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/extract_precompiled_script_plugin/build.gradle

**Comment by etiennestuder** [comment]
Closing this due to lack of an answer. Makes me wonder why I even put time into creating an example project.

**Comment by p-** [comment]
Hi @etiennestuder

Thanks very much for the sample project, that's exactly what I was looking for!

>Closing this due to lack of an answer

Sorry, I had to try it out first.

>Did you consider this approach?
>https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/extract_precompiled_script_plugin

For the moment I prefer this approach over the precompiled script as it makes it possible to hold everything in a single file.

**Comment by etiennestuder** [comment]
Great to hear. Glad to help a Swiss fellow :-)
