### ISSUE TITLE
Add new jOOQ 3.15 generator configurations

### ISSUE THREAD

**Issue by saibotma** [etiennestuder/gradle-jooq-plugin#179]
I can't find an option to set the new jOOQ 3.15 generator configurations listed [here](https://www.jooq.org/doc/3.0/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-annotations/).

Especially `kotlinSetterJvmNameAnnotationsOnIsPrefix` would be important for me.

**Comment by etiennestuder** [comment]
> I can't find an option to set the new jOOQ 3.15 generator configurations listed [here](https://www.jooq.org/doc/3.0/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-annotations/).

Where are you looking for it?

> Especially kotlinSetterJvmNameAnnotationsOnIsPrefix would be important for me.

```
...
    generate {
                        ...
                        fluentSetters = false
                        kotlinSetterJvmNameAnnotationsOnIsPrefix =true
                        ...
    }
```

Ensure you are using a version of jOOQ that contains the new APIs. See documentation:
- [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#specifying-the-jooq-version-and-edition)
- [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#enforcing-the-jooq-configuration-xml-schema-version)
- [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#changelog)

Version 6.0 has them by default for sure.
