### ISSUE TITLE
gradle-jooq-plugin should not override jOOQ dependency if specified in dependencies

### ISSUE THREAD

**Issue by lukaseder** [etiennestuder/gradle-jooq-plugin#18]
A jOOQ user is running into issues because a very old jOOQ version is being pulled by this Gradle plugin. The issue is documented here:
http://stackoverflow.com/q/38727927/521799

Essentially:

```groovy
dependencies {
    ...
    // Expected jOOQ version
    compile "org.jooq:jooq:3.8.4"
    compile "org.jooq:jooq-meta:3.8.4"
    compile "org.jooq:jooq-codegen:3.8.4"
}

... 

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        // Overridden jOOQ version: 3.4.1
        classpath 'nu.studer:gradle-jooq-plugin:1.0.5'
        ...
    }
}
```

- Is it possible for the `gradle-jooq-plugin` to detect if jOOQ is already a dependency, and then use that version rather than the default?
- If not, does the `gradle-jooq-plugin` currently log the fact that it is using an old / hard-wired version?

**Comment by oehme** [comment]
Hey Lukas,

this is the same as #12, let's continue the discussion there.

Cheers,
Stefan

**Comment by lukaseder** [comment]
OK, closing this as a duplicate of #12
