### ISSUE TITLE
jooq plugin with liquibase has dependency mismatch issue

### ISSUE THREAD

**Issue by thedewpoint** [etiennestuder/gradle-jooq-plugin#181]
When running the jooq-plugin 3.15 with the jooq-meta-extensions-liquibase, it throws an error 

```
java.lang.NoSuchMethodError: liquibase.resource.FileSystemResourceAccessor: method 'void <init>()

```
I checked through the source code, and it looks like the init method was removed in newer versions. When I run the gradle dependencies task on it I see that the jooq-meta-extensions-liquibase is pulling in  liquibase-core transitive dependency at version 4.3.3.

```
+--- org.jooq:jooq-meta-extensions-liquibase -> 3.15.0
|    +--- org.jooq:jooq-meta-extensions:3.15.0
|    |    +--- org.jooq:jooq-meta:3.15.0 (*)
|    |    \--- com.h2database:h2:1.4.200
|    \--- org.liquibase:liquibase-core:3.8.8 -> 4.3.3
|         \--- javax.xml.bind:jaxb-api:2.3.0 -> 2.3.1 (*)

```
I was able to fix this by placing this configuration in my build.gradle.kts file

```kotlin
configurations.all {
	resolutionStrategy.eachDependency {
		if (requested.group == "org.liquibase" && requested.name == "liquibase-core") {
			useVersion("3.9.0")
			because("jooq + liquibase integration doesn't work at version 4 ");
		}
	}
}
```
I'm not sure how to fix this the right way but wanted to raise awareness of it.

**Comment by lukaseder** [comment]
Seems related: https://github.com/jOOQ/jOOQ/issues/11659. Can you downgrade Liquibase for the purpose of using it with jOOQ's code generator? Alternatively, you don't have to use jOOQ's `LiquibaseDatabase`. It's always better to run code generation against an *actual* database, not a simulated one...

**Comment by etiennestuder** [comment]
> I'm not sure how to fix this the right way but wanted to raise awareness of it.

That's surely one way to downgrade a dependency's version.

Note that if only the jOOQ code generation is affected, you can reduce the code to just the `jooqGenerator` configuration (instead of all configurations).

And just for the record: this GH issue is not a gradle-jooq-plugin issue, but a standard case of how to influence Gradle dependency resolution.

**Comment by thedewpoint** [comment]
@lukaseder I did downgrade my liquibase version, the problem is that org.jooq:jooq-meta-extensions-liquibase is pulling in its own upgraded version of liquibase-core transitively. I have to override the transitive dependency to get it working.

**Comment by lukaseder** [comment]
> I have to override the transitive dependency to get it working.

Yes, that's what I meant

**Comment by thedewpoint** [comment]
@lukaseder ah sorry I misunderstood, yea that is what I ended up doing, the relevant configuration is above. Just wanted to let you guys know, sorry if this is in the wrong place.

**Comment by lukaseder** [comment]
> Just wanted to let you guys know, sorry if this is in the wrong place.

Sure, thanks again for your report. Always good to get pings to learn about what problems people run into most. Helps prioritise fixing things :)

**Comment by etiennestuder** [comment]
Thanks for the feedback, @thedewpoint .
