### ISSUE TITLE
Task not UP-TO-DATE

### ISSUE THREAD

**Issue by cdalexndr** [etiennestuder/gradle-jooq-plugin#185]
Running the `generateJooq` task always do work, even if inputs are specified:
`generateJooq.inputs.files fileTree(dir: 'src', include: '**/*.sql')`
Result:
```
 Task :backend:server:generateJooq
Excluding []
Caching disabled for task ':backend:server:generateJooq' because:
  Caching has not been enabled for the task
Task ':backend:server:generateJooq' is not up-to-date because:
  Task.upToDateWhen is false.
```

I don't want to run the task if no migration scripts have changed.

**Comment by cdalexndr** [comment]
Using `generateJooq.outputs.upToDateWhen { true }` has no effect,
and `generateJooq.upToDateWhen { true }` throws error:
` Could not find method upToDateWhen() for arguments [server_6kk78kxzzp7jpnn3i4d4mplf3$_run_closure14@794f06fa] on task ':backend:server:generateJooq' of type nu.studer.gradle.jooq.JooqGenerate.
`

**Comment by etiennestuder** [comment]
The README explains how to do it, and it also refers to a full example.
