### ISSUE TITLE
Can't target specific schema using the Kotlin DSL

### ISSUE THREAD

**Issue by dtbullock** [etiennestuder/gradle-jooq-plugin#186]
I am not having success tailoring my catalog/schema usage in the Kotlin DSL.  The following does not compile, although it seems to be the logical translation of the examples given in [Read two or more schemas from one or more specific catalogs](https://www.jooq.org/doc/3.1/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-catalog-and-schema-mapping/).

The following is from IntelliJ highlighting.  Gradle complains of the same issues when compiling the build.  I am using `JooqEdition.TRIAL_JAVA_8`

![image](https://user-images.githubusercontent.com/3402268/129822262-863dea4e-7cbb-474d-beb8-17e86f792f6b.png)

(And despite that page alleging that schema inclusion "works in a similar fashion as the includes and excludes elements", using a regex for `inputSchema = ` or `inputCatalog =` fails to match any schema).

**Comment by lukaseder** [comment]
You're not setting the `inputCatalog` or `schemata` value on your `catalogs` reference. You're setting it on your `database` reference. Your configuration should look more like this:

```kotlin
database.apply {
    catalogs.add(CatalogMappingType().apply {
        inputCatalog = "dash"
        schemata.addAll(arrayOf(
            SchemaMappingType().apply {
                inputSchema = "dbo"
            },
            SchemaMappingType().apply {
                inputSchema = "scp"
            }
        ))
    })
}
```

You can see a related example here: https://github.com/etiennestuder/gradle-jooq-plugin#gradle-kotlin-dsl-4 (look for the `forcedTypes` configuration).

I'm not sure if there's a kotlin convenience syntax that works as leniently as the Groovy one when dealing with lists.

> (And despite that page alleging that schema inclusion "works in a similar fashion as the includes and excludes elements", using a regex for `inputSchema = ` or `inputCatalog =` fails to match any schema).

Regular expressions aren't supported in those configuration elements (`inputCatalog` and `inputSchema`), see https://github.com/jOOQ/jOOQ/issues/9784

**Comment by dtbullock** [comment]
OK, that works.  Groovy continues to confound me, even though I refuse to use it.

I see now that the `schemata` member of  `Database` is a `List<SchemaMappingType>` and calling `apply()` would only get me a block where I could call `add()` conveniently, and not a DSL context which might have a `schema` member which took a block configuring a `SchemaMappingType` and implicitly adding it to the collection for me.

One frustration was (and it is probably no fault directly of `gradle-jooq-plugin`) that IntelliJ's CTRL+Q would not give me any useful information about the types in `org.jooq.meta.jaxb` at all.  Who was to know that instantiating an instance of `SchemaMappingType` and adding it to the collection was the desired action that is automagically done by Groovy?  No sort of IntelliSense would ever get me there, I think ... it has to be doco.  

Anyway, thanks for jumping in on this so quickly.   Despite frustrations, I am liking JOOQ a lot.

**Comment by etiennestuder** [comment]
@dtbullock the implementation of the gradle jooq plugin uses groovy's dynamic method resolution to be able to deal with new APIs being added to the jooq generator schema _without_ requiring a new version of the gradle jooq plugin. This is at the expense of code assistance in IDEs. At the time this plugin was written, there was no Kotlin DSL, yet. Today, I might choose a different approach when starting from scratch, but that train has left.
