### ISSUE TITLE
Provide a code generation example that demonstrates manual code generation with a dedicated output directory

### ISSUE THREAD

**Issue by mcohen75** [etiennestuder/gradle-jooq-plugin#197]
In some situations, there are benefits to running code generation on an as-needed basis and checking in generated soruce files. 

For example, consider a situation where a service connects to a shared database but does not have ownership of the database schema. Providing access to the schema at build time in some environments can be time-consuming. We could copy database creation/maintenance scripts, or expose the latest version of the database via some other mechanism and make sure it's available from all build environments.

At Indeed we have a couple of projects like this as part of a migration away from a monolithic database. We've decided to temporarily generate models manually on an as-needed basis (often just once).

If there's interest in an example like this I'd be happy to contribute one.

I think the following would be appropriate:
1. Add a source directory for generated JOOQ classes (src/main/jooq perhaps).
2. Set target.directory to the added source directory ('src/main/jooq')
3. Set generateSchemaSourceOnCompilation = false.

**Comment by etiennestuder** [comment]
Thanks, @mcohen75. Feel free to submit such an example. I can then add it to the [example](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example) section. I'll close this issue for now, but you can reopen if/once you have submitted an example for the use case you described above.
