### ISSUE TITLE
How to use matcher strategy with kotlin DSL?

### ISSUE THREAD

**Issue by stackunderflow111** [etiennestuder/gradle-jooq-plugin#198]
Hi, I want to add a `Po` suffix to all the POJOs generated from the tables, and I need to do it in the Kotlin DSL. Below is an approach I found. It works, but the code doesn't look very concise.

```kotlin
jooq {
    configurations {
        create("main") {
            jooqConfiguration.apply {
                generator.apply {
                    // omitted
                    strategy.apply {
                        matchers = Matchers()
                            .withTables(
                                MatchersTableType()
                                    .withPojoClass(
                                        MatcherRule()
                                            .withExpression("\$0_Po")
                                            .withTransform(MatcherTransformType.PASCAL)
                                    )
                            )
                    }
                }
            }
        }
    }
}
```

I am wondering, is there another approach that looks better?

**Comment by lukaseder** [comment]
What's bothering you in particular? The jOOQ configuration hierarchy, or the kotlin DSL? What would you expect, instead?

**Comment by stackunderflow111** [comment]
Sorry, I raised this question without looking at the plugin's source code. I just read the source code and seems that the Groovy DSL config goes through the `generationTool` method, which configures the `org.jooq.meta.jaxb.Configuration` object through a `JaxbConfigurationBridge`. However, this is not the case for the Kotlin DSL and we work with the `org.jooq.meta.jaxb.Configuration` directly. Therefore the issue does not relate to the plugin.

Sorry again and I'm closing it.
