### ISSUE TITLE
Cannot set custom Strategy name if also Matchers are defined

### ISSUE THREAD

**Issue by LimmaPaulus** [etiennestuder/gradle-jooq-plugin#199]
Line 221 on JooqGenerate.java sets name of strategy to null if getMatchers() returns non null value

![image](https://user-images.githubusercontent.com/14800398/146895274-3a8d619f-43bd-42d1-9241-2455389bbc52.png)
https://github.com/etiennestuder/gradle-jooq-plugin/blob/88321bf4a8c87bae8d3f1a66696fec179d177017/src/main/groovy/nu/studer/gradle/jooq/JooqGenerate.java#L221

I don't really get idea of this. Now with the following configuration (Kotlin DSL)
```Kotlin
strategy.name = "org.example.CustomGeneratorStrategy"
strategy.matchers = Matchers().withTables(
    MatchersTableType().withPojoImplements(
        "org.example.JooqPojo"
    )
)

```

the generated XML is as follows (strategy name is wiped out)

```XML
    <generator>
        <name>org.jooq.codegen.KotlinGenerator</name>
        <strategy>
            <matchers>
                <tables>
                    <table>
                        <pojoImplements>org.example.JooqPojo</pojoImplements>
                    </table>
                </tables>
            </matchers>
        </strategy>
```

So effectively I'm not able to set both custom Strategy and Matchers.

**Comment by etiennestuder** [comment]
> So effectively I'm not able to set both custom Strategy and Matchers.

Yes, this is intentional since jOOQ's XSD does not allow to set both:

![image](https://user-images.githubusercontent.com/231070/146950144-7cfc821e-19ec-455a-a2ea-16de76b4392e.png)

**Comment by LimmaPaulus** [comment]
Ok, thanks. Sorry for the noise.
