### ISSUE TITLE
Problem with file location

### ISSUE THREAD

**Issue by RealYusufIsmail** [etiennestuder/gradle-jooq-plugin#200]
so i have this 
```gradle
jooq {
    version = '3.15.1'
    edition = JooqEdition.OSS
    configurations {
        main {
            generationTool {
                logging = org.jooq.meta.jaxb.Logging.WARN
                jdbc {
                    driver = 'org.h2.Driver'
                    url = 'jdbc:h2:file:/Users/YusufIsmail/OneDrive/sqldb/sql'
                    user = sqlUser
                    password = sqlPassword
                }
                generator {
                    name = 'org.jooq.codegen.JavaGenerator'
                    database {
                        name = 'org.jooq.meta.h2.H2Database'
                        includes = '.*'
                        excludes = ''
                    }
                    generate {
                        deprecated = false
                        records = false
                        immutablePojos = false
                        fluentSetters = false
                    }
                    target {
                        packageName = 'io.github.realyusufismail.jooq'
                        directory = 'build/generated-sources'
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}
```
Instead of having 'jdbc:h2:file:/Users/YusufIsmail/OneDrive/sqldb/sql' I want it to have something like database/build
instead of getting the user
so when other people use the database they dont have to change it
I tried doing ./database/build/sqldb/sql.mv.db
It cause a problem
I saw this https://stackoverflow.com/questions/30596150/how-to-use-a-path-relative-to-project-root-to-h2-db-file-configuration-with-play
but that does not solve my problem since the public_ folder is not created which is an issue.

This is my db
![image](https://user-images.githubusercontent.com/67903886/147292150-1a5b40ca-5c90-4a67-bf38-2dd8e897fc3f.png)

**Comment by RealYusufIsmail** [comment]
<img width="279" alt="Screenshot 2021-12-23 at 22 07 37" src="https://user-images.githubusercontent.com/67903886/147295186-e76e8a87-5c93-46a9-8983-3d64909f85da.png">
Should look like this

**Comment by etiennestuder** [comment]
This is not really a question related to the gradle jooq plugin.

Still, some thoughts:
- why don't you use `~` to refer to the user's home folder to avoid hard-coding any username?
- you could also replace the JDBC URL (or parts of it) with a property with some default value that can be overridden at invocation time from the cmd line or IDEA
