### ISSUE TITLE
Example: jooq-example-configure-jooq-with-flyway migration location problem

### ISSUE THREAD

**Issue by chrismaster** [etiennestuder/gradle-jooq-plugin#211]
Example: jooq-example-configure-jooq-with-flyway 
With db/migration as path for the migrations, everything is ok. Since this is the default search path for flyway.
If you put it into any other folder and change inputs.files(fileTree('src/main/resources/db/migration' to the folder, it wont work.

If you change
inputs.files(fileTree('src/main/resources/db/migration'
inputs.files(fileTree('src/main/resources/db/migrationn'
and the folder db.migration to db.migrationn it wont find the migrations.

Error:
Unable to resolve location classpath:db/migrationn. Note this warning will become an error in Flyway 7.
No migrations found. Are your locations set up correctly?

Any help on this?

**Comment by etiennestuder** [comment]
This is more of a flyway question. Please ask for assistance on the Flyway project.

**Comment by chrismaster** [comment]
In flyway it works.
The setting for flyway+gradle would be
locations = ['db/migration'] or 
locations = ['db/migrationn'] for the above example.

but in the jooq example
inputs.files(fileTree('src/main/resources/db/migration'))
        .withPropertyName('migrations')
        .withPathSensitivity(PathSensitivity.RELATIVE)
won't work. It just does for db/migration the job, cause db/migration is the default flyway search path. But has nothing to do with the inputs.files.... setting in generateJooq

Change the example to some other path and it is broken....

**Comment by etiennestuder** [comment]
This has nothing to do with the gradle-jooq-plugin. All you pass to the JooqGenerate task is the location of the migration scripts such that they are included as an input when calculating the fingerprint of the JooqGenerate task. None of this has any effect on the Flyway task.

This example changes the location of the migration scripts where Flyway will search them...

```
flyway {
    configurations = ['flywayMigration']
    locations = ['filesystem:src/main/resources/db/migration2']
    url = 'jdbc:h2:~/test;AUTO_SERVER=TRUE'
    user = 'sa'
    password = ''
}
```

...and then also informs the JooqGenerate task where the migration scripts are located.

```
tasks.named('generateJooq').configure {
    // ensure database schema has been prepared by Flyway before generating the jOOQ sources
    dependsOn tasks.named('flywayMigrate')

    // declare Flyway migration scripts as inputs on the jOOQ task
    inputs.files(fileTree('src/main/resources/db/migration2'))
        .withPropertyName('migrations')
        .withPathSensitivity(PathSensitivity.RELATIVE)

    // make jOOQ task participate in incremental builds (and build caching)
    allInputsDeclared = true
}
```
