### ISSUE TITLE
Generated code is not refreshed on database schema update

### ISSUE THREAD

**Issue by plinyar** [etiennestuder/gradle-jooq-plugin#22]
If I change database table structure, say add new column (I use postgres), and run
`gradlew generateMainJooqSchemaSource`
 then it says 
`:generateMainJooqSchemaSource UP-TO-DATE`
, which means it doesn't change anything in generated code (it doesn't indeed).

The only workaround now is to delete the generated files before running the build.

It would be nice to have it recognize database structure changes, or at least to have another gradle task which forces code re-generation.

**Comment by plinyar** [comment]
Oh, sorry, I forgot that gradle has "--rerun-tasks" switch that force code-regeneration. But unfortunately I cannot pass this switch when running the task in IntelliJ IDEA (I use it) and for that I have to leave the IDE.

**Comment by etiennestuder** [comment]
You can pass switches from IDEA to Gradle. See screenshot.

<img width="829" alt="screen shot 2016-09-26 at 04 31 41" src="https://cloud.githubusercontent.com/assets/231070/18820958/3c3f65de-83a2-11e6-9eb7-9d6c92ac26a9.png">

**Comment by etiennestuder** [comment]
You could also run `cleanGenerateMainJooqSchemaSource` to remove the generated sources and then run `generateMainJooqSchemaSource`.

**Comment by etiennestuder** [comment]
I do not plan for the jooq plugin to detect db changes. This can be implemented specifically by the user of the plugin. Or you use the jooq plugin together with the flyway plugin, which will take care of it, too.

**Comment by plinyar** [comment]
Thanks for the ideas

**Comment by lukaseder** [comment]
Just in case, here's how to configure the plugin to read Flyway's `schema_version` table:
https://github.com/jOOQ/jOOQ/blob/a6368da4559b834161dfb45e695d8105c15aaef3/jOOQ-examples/jOOQ-flyway-example/pom.xml#L127

That'll work in Gradle just the same by adding this `schemaVersionProvider` flag.
