### ISSUE TITLE
Cache task output even if DB name changes?

### ISSUE THREAD

**Issue by andrewparmet** [etiennestuder/gradle-jooq-plugin#231]
I'm curious if I can refine my CI workflow. The way it works now is I have a test DB available in CI that I use to run jOOQ, and I have enabled caching:

``` kotlin
tasks.named<JooqGenerate>("generateJooq") {
    inputs.dir("$rootDir/db/liquibase")
    allInputsDeclared.set(true)
}
```

We have a DB name that's randomized and passed into Gradle via a Gradle property when we build and test the project, but then when we run subsequent tasks, e.g. `jacocoTestReport`, the tasks fail since we're not always giving the DB name as a property anymore. It looks like the task thinks its out of date because we're not passing it the same DB name - we default to the name on local dev machines if not overridden by the property.

Is there a way to "use the generated code that's there already" so long as the liquibase files themselves haven't changed? That is, have the caching work on the DB input alone rather than on the config as well?

Thanks!

**Comment by etiennestuder** [comment]
> Is there a way to "use the generated code that's there already" so long as the liquibase files themselves haven't changed? That is, have the caching work on the DB input alone rather than on the config as well?

Yes, see section Examples in the README:
https://github.com/etiennestuder/gradle-jooq-plugin#examples
_Using Flyway in combination with jOOQ to generate the schema and jOOQ sources_

**Comment by andrewparmet** [comment]
That example says it does actually depend on the configuration:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/configure_jooq_with_flyway/build.gradle#L55

> `// - the jOOQ configuration has changed (Jdbc, Generator, Strategy, etc.)`

I specifically don't want to regenerated if the jOOQ configuration changes, or at least just not if the JDBC configuration changes.

**Comment by etiennestuder** [comment]
> That example says it does actually depend on the configuration:

That example covers your requirement of _"use the generated code that's there already" so long as the liquibase files themselves haven't changed_.

> I specifically don't want to regenerated if the jOOQ configuration changes, or at least just not if the JDBC configuration changes.

That's covered in the example _Normalizing the jOOQ config to ensure relocatability_.

**Comment by andrewparmet** [comment]
Ah, perfect. Thanks!
