### ISSUE TITLE
Conflict with other org.jooq projects besides jOOQ

### ISSUE THREAD

**Issue by sargue** [etiennestuder/gradle-jooq-plugin#24]
The new (version 2.0) plugin seem to treat all dependencies with group `org.jooq` as part of the jOOQ product package. This breaks other projects like jOOL.

Relevent parts of my `build.gradle`:

```
dependencies {
    jooqRuntime 'org.mariadb.jdbc:mariadb-java-client:1.5.1-RC'

    compile "org.jooq.pro:jooq"
    compile 'org.jooq:jool:0.9.11'
}

jooq {
    version = '3.8.4'
    edition = 'PRO'
    ...
}
```

If I list the dependencies:

```
...
+--- org.jooq.pro:jooq: -> 3.8.4
+--- org.jooq:jool:0.9.11 -> org.jooq.pro:jool:3.8.4 FAILED
...
```

Only the artifact with name 'jooq' (I think, maybe @lukaseder could confirm) should be modified by the plugin.

**Comment by etiennestuder** [comment]
Thanks for reporting this. Some packages do follow the 3.8.5 versions, some do not. I think I will explicitly whitelist in the plugin those packages to be included in the version transformation: 
- jooq-meta-extensions
- jooq-meta
- jooq-codegen-maven
- jooq-codegen
- jooq-parent
- jooq-scala
- jooq

**Comment by etiennestuder** [comment]
Fixed in release 2.0.1.

**Comment by sargue** [comment]
Thanks @etiennestuder for the fast fix and release.

Also, I see that you've finally decided to check if the artifact name just starts with _jooq_ instead of a hard coded artifact list. I think it makes sense. Got your blessing @lukaseder ?

**Comment by lukaseder** [comment]
> Got your blessing @lukaseder ?

Yes, that's a reasonable assumption. All future jOOQ artifacts (if any) will be prefixed with jOOQ.
