### ISSUE TITLE
Groovy DSL fields not working 

### ISSUE THREAD

**Issue by jarasez** [etiennestuder/gradle-jooq-plugin#308]
I am trying to define synthetic primary keys like in the docs: 
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-objects/codegen-database-synthetic-pks/

Error I get: 
 Invalid property: 'field' on extension 'jooq.main.generationTool.generator.database.syntheticObjects.primaryKeys.primaryKey', value: COLUMN1. Please check the current XSD: https://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd.

**Comment by lukaseder** [comment]
For the record, this question has also been asked here:

**Comment by etiennestuder** [comment]
See here:
https://github.com/etiennestuder/gradle-jooq-plugin/issues/282
