### ISSUE TITLE
New release including jOOQ 3.16.6

### ISSUE THREAD

**Issue by jippeholwerda** [etiennestuder/gradle-jooq-plugin#326]
Would it be possible to make a new release containing 3.16.6? Currently, we cannot upgrade jOOQ because of https://github.com/jOOQ/jOOQ/issues/13247. I noticed the version already has been bumped but not yet released.

Thanks!

**Comment by etiennestuder** [comment]
No new release is needed. You can configure the version you want to use. See
- https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#specifying-the-jooq-version-and-edition
- https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#enforcing-the-jooq-configuration-xml-schema-version

**Comment by jippeholwerda** [comment]
Cool! I already specified the jOOQ version, but didn't know about specifying the code generation version. Thanks!

**Comment by etiennestuder** [comment]
Great. Yes, specifying the jOOQ version in the DSL defines what version will be used when running the code generator. And the version you specify in the buildscript classpath determines what APIs you can actually configure via DSL.
