### ISSUE TITLE
Generator fails when using org.jooq.util.JPADatabase

### ISSUE THREAD

**Issue by raulgd** [etiennestuder/gradle-jooq-plugin#34]
Hi,

As on the project I'm in we are already using Hibernate with JPA, I want to use the JPA translation features of JOOQ. I'm using JOOQ version 3.9.0

When I try to build, I get the following error:
```
Error : org.jooq.util.jpa.JPADatabase
java.lang.ClassNotFoundException: org.jooq.util.jpa.JPADatabase
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.jooq.util.GenerationTool.loadClass(GenerationTool.java:668)
        at org.jooq.util.GenerationTool.run(GenerationTool.java:294)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:199)
        at org.jooq.util.GenerationTool.main(GenerationTool.java:171)
```

Although I know the class is in there, included by the jooq-meta-extensions dependency.
This is my jooq plugin configuration:
```groovy
jooq {
    version = '3.9.0'
    edition = 'OSS'
    basic(sourceSets.main) {
        generator {
            database {
                name = 'org.jooq.util.jpa.JPADatabase'
                properties {
                    property {
                        key = 'packages'
                        value = 'myapp.entities'
                    }
                }
            }
        }
    }
}
```

Am I missing something? or does the plugin has issues using the JOOQ JPA integration feature?

Thanks

**Comment by raulgd** [comment]
Ok, I'm closing the issue, as for fixing this, I added multiple jooqRuntime statements each with the required dependencies for running the generator.
I ended up adding Hibernate 5.2, jooq-meta-extensions and commons-logging with the jooqRuntime so it worked.

Thanks

**Comment by lkw1989** [comment]
for example

jooqVersion = 3.8.x
```
dependencies {
    jooqRuntime("org.jooq:jooq-meta-extensions:${jooqVersion}")
    jooqRuntime("commons-logging:commons-logging:1.2")
}
```

jooqVersion = 3.9.x
```
dependencies {
    jooqRuntime("org.jooq:jooq-meta-extensions:${jooqVersion}")
    jooqRuntime("commons-logging:commons-logging:1.2")
    jooqRuntime("org.hibernate:hibernate-core:5.2.11.Final")
}
```

**Comment by woniper** [comment]
for example

jooqVersion = 3.8.x

dependencies {
    jooqRuntime("org.jooq:jooq-meta-extensions:${jooqVersion}")
    jooqRuntime("commons-logging:commons-logging:1.2")
}
jooqVersion = 3.9.x

dependencies {
    jooqRuntime("org.jooq:jooq-meta-extensions:${jooqVersion}")
    jooqRuntime("commons-logging:commons-logging:1.2")
    jooqRuntime("org.hibernate:hibernate-core:5.2.11.Final")
}

**Comment by lukaseder** [comment]
@etiennestuder This kind of question is being asked again and again, including on the jOOQ issue tracker: https://github.com/jOOQ/jOOQ/issues/6866, and there's an open issue on the plugin for this: https://github.com/etiennestuder/gradle-jooq-plugin/issues/54

I'd like to have this documented somewhere, i.e. how the `jooq-meta-extensions` dependency should be correctly configured. Is that worth adding to the [`README.md`](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md) ?

**Comment by etiennestuder** [comment]
Thanks for pointing this out. I'll take a look @lukaseder.
