### ISSUE TITLE
Create a concrete type safe method to add a configuration to the JooqExtension

### ISSUE THREAD

**Issue by JLLeitschuh** [etiennestuder/gradle-jooq-plugin#35]
I'm writing my build using [gradle-script-kotlin](https://github.com/gradle/gradle-script-kotlin) which allows you to write your build in kotlin which has infered typing.

Methods like this one don't play wel with a statically typed language:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/src/main/groovy/nu/studer/gradle/jooq/JooqExtension.groovy#L45

**Comment by etiennestuder** [comment]
This plugin is leveraging Groovy quite a bit. All the way down to the actual jooq configuration. It's all using dynamic mechanisms.

I plan to release a new version of the plugin where the config is in the original jOOQ XML instead of a DSL in the Gradle build. This will be Groovy agnostic.

**Comment by JLLeitschuh** [comment]
Once I started using the plugin I understood why it was written this way.

**Comment by etiennestuder** [comment]
I'm going to close this issue since there is nothing that can be done when using the Groovy-based (dynamic) approach. It will be implicitly fixed in a new major version as described above.

**Comment by etiennestuder** [comment]
As of 5.x, the gradle-jooq-plugin supports the Gradle Kotlin DSL as a first-class citizen. See the README file:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md

See this complete example written with the Gradle Kotlin DSL:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts
