### ISSUE TITLE
How to configure jOOQ with Testcontainer and Flyway.

### ISSUE THREAD

**Issue by stillya** [etiennestuder/gradle-jooq-plugin#365]
Can you provide, please, example of configuration jOOQ with Testcontainer and Flyway in your Plugin DSL? I think it's common case for many users.

**Comment by etiennestuder** [comment]
There is already an example for Flyway:
https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/configure_jooq_with_flyway

Due to lack of time, I do not intend to add an example that involves Testcontainers.

**Comment by SightStudio** [comment]
Although this issue is closed, combining Using Testcontainer and flyway is quite common.  (like @stillya says)

Since I spent lots of time on this configuration work, I can make example for it.

@etiennestuder
