### ISSUE TITLE
handle multiple schemas

### ISSUE THREAD

**Issue by iceback** [etiennestuder/gradle-jooq-plugin#37]
At least I haven't seen how to do it.  I've tried a couple of list constructs in inputSchema and I've tried to iterate over a list of schema names.  Is the only alternative to duplicate the jooq{} block for each schema?

**Comment by oceantume** [comment]
I had the same question today and since I found this open issue while searching I figured I would answer with the solution (see the gradle code sample): https://www.jooq.org/doc/3.9/manual/code-generation/codegen-advanced/codegen-config-catalog-and-schema-mapping/#N3F5D7

I believe having one jOOQ configuration per schema would prevent the generated code from being aware of cross-schema foreign keys, which may prevent using some features.

**Comment by iceback** [comment]
Still at sea here.  I see this as saying jooq can handle multiple schemata, which is great, but how does one specify them in the plugin's jooq{} block such that the plugin will expand the list of schema (I'm living with one catalog)

**Comment by oceantume** [comment]
Maybe I misunderstood your question and it's not the same problem as I had today, but I wanted to include two schemas from a MySQL server and the following code is roughly what it ended up like. It ends up generating one java package per schema under the package name i provide.

`
jooq {
    version = '3.8.6'
    edition = 'OSS'

    mydatabase(sourceSets.main) {
        jdbc {
            driver = 'com.mysql.jdbc.Driver'
            url = dbGenJdbcUrl
            user = dbGenJdbcUser
            password = dbGenJdbcPassword
            properties {
                property {
                    key = 'ssl'
                    value = 'false'
                }
            }
        }
        generator {
            name = 'org.jooq.util.DefaultGenerator'
            strategy {
                name = 'org.jooq.util.DefaultGeneratorStrategy'
            }
            database {
                name = 'org.jooq.util.mysql.MySQLDatabase'
                includes = '.*'
                schemata {
                    schema {
                        inputSchema = 'first'
                    }
                    schema {
                        inputSchema = 'second'
                    }
                }
            }
            generate {
                deprecated = false
                interfaces = true
            }
            target {
                packageName = 'my.package.generated.db'
            }
        }
    }
}
`

**Comment by lukaseder** [comment]
Indeed, @oceantume's solution should work. We've recently improved the manual sections by adding some gradle configuration examples along with the Maven ones. There are examples of multiple `inputSchema` configurations here:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-catalog-and-schema-mapping

**Comment by etiennestuder** [comment]
Closing this issue since a solution is available and documented.
