### ISSUE TITLE
Classes from `org.jooq` package in plugin's API force ues of afterEvaluate

### ISSUE THREAD

**Issue by britter** [etiennestuder/gradle-jooq-plugin#371]
## Summary

Non-lazy types from the `org.jooq` package in the plugin's API force me to use `afterEvaluate` if I want to connect configuration values of this plugin with other lazy configuration values.

## Context

We have a medium sized build and in order to centralize common configuration for the gradle-jooq-plugin we want to build a convention plugin on top of it. Our convention plugin provides an extension where users can configure e.g. the database name to use for code generation:

```kotlin
interface MyJooqExtension {
    val databaseName: Property<String>
}
```

Now in my convention plugin I want to set the database name on `jooq.configuration.main.generationTool.generator.database.name`. However `name` is of type String not `Property<String>`:

```kotlin
val extension = extensions.create<MyJooqExtension>("myJooq")

jooq {
  configurations {
    main {
       generationTool {
        generator {
          database {
            name = extension.databaseName.get()
          }
        } 
      }
    }
  }
}
```

The code above does not work because by the time the plugin is applied and `databaseName` is accessed, it does not yet have a value set. The only way around this is to wrap this part of my plugin into `afterEvaluate`. This leads to ordering problems when several plugins need to use `afterEvaluate` set configuration values.

## Possible fix

The only way around this that I see is to duplicate all types from `org.jooq` that are used in the plugin's API and change their fields to provider API.

**Comment by etiennestuder** [comment]
Closing this issue since it will not be addressed anytime soon.
