### ISSUE TITLE
Jooq version upgrade to 3.17.0

### ISSUE THREAD

**Issue by venmani** [etiennestuder/gradle-jooq-plugin#377]
I need to use Jooq for Reactive transactional queries. This ability is available only from org.jooq:jooq:3.17.0 (not in the previous versions). 

While I am using nu.studder.jooq plugin, it is bringing jooq 3.16.0 version and I am not able to override/force to new version. So if we are updating jooq version in this library it will be useful or else if I get any way to override the version provided by this library in my application that also fine. 
Note: I am using micronaut framework to develop my application. 

Please help me in this.

**Comment by etiennestuder** [comment]
The Readme explains how to use a newer version than the one that is used by this plugin by default.
