### ISSUE TITLE
Standalone usage

### ISSUE THREAD

**Issue by sbuettner** [etiennestuder/gradle-jooq-plugin#40]
First of all, great plugin. Really simplifies usage of JOOQ code generation.

We would like to use this plugin by just calling the generated task but not during the build process of a project. Is there a way to disable the build dependencies defined in: https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/src/main/groovy/nu/studer/gradle/jooq/JooqPlugin.groovy#L114 ?

**Comment by etiennestuder** [comment]
@sbuettner See my comment here:
https://github.com/etiennestuder/gradle-jooq-plugin/issues/36#issuecomment-282331893

Not the nicest solution but at least it should work as a workaround.

**Comment by etiennestuder** [comment]
Closing this under the assumption that the workaround is good enough.

**Comment by sbuettner** [comment]
@etiennestuder Thanks for the response.

**Comment by etiennestuder** [comment]
@sbuettner See this comment for a full example (one-liner):
https://github.com/etiennestuder/gradle-jooq-plugin/issues/36#issuecomment-283705346
