### ISSUE TITLE
Postgres Custom Binder Issue

### ISSUE THREAD

**Issue by mertemin** [etiennestuder/gradle-jooq-plugin#42]
I am trying to implement custom data binding (explained [here](https://www.jooq.org/doc/3.9/manual/code-generation/custom-data-type-bindings/)) with gradle. My configuration looks like:
```
jooq {
    version = '3.9.1'
    edition = 'OSS'
    database(sourceSets.main) {
        jdbc {
            driver = 'org.postgresql.Driver'
            url = 'jdbc:postgresql://localhost:5432/test'
            user = 'mert'
            password = ''
        }
        generator {
            name = 'org.jooq.util.DefaultGenerator'
            database {
                name = 'org.jooq.util.postgres.PostgresDatabase'
                inputSchema = 'public'
                includes = '.*'
                excludes = 'SCHEMA_VERSION'
                
                forcedTypes {
                	forcedType {
                		userType = 'com.google.gson.JsonElement'
                		binding = 'com.mert.test.PostgresJSONGsonBinding'
                		expression = '.*JSON.*'
                		types = '.*'
                	}
                }
            }
            target {
                packageName = 'com.mert.test.db'
                directory = '/Users/mert/Projects/test/src/main/java'
            }
        }
    }
}
```

The code generation is fine. But custom data binding is not happening. README's `forcedType` example is different, and I am not sure I am doing the right thing. I went over the logs, but there isn't any warning or error regarding `forcedType` or any sort.

I also tried with the following forcedType config, but again no custom binding is created:
```
forcedType {
	name = 'com.mert.test.PostgresJSONGsonBinding'
	expression = '.*JSON.*'
	types = '.*'
}
```

This is using postgres jdbc 9.4.1212 and jooq plugin's v2.0.4.

**Comment by lukaseder** [comment]
Are you sure your column names are using capital names? Because the PostgreSQL default case is lower case, so try any of these:

```
// case sensitive, lower case regex
expression = '.*json.*'

// case insensitive regex
expression = '(?i:.*json.*)'
```

**Comment by etiennestuder** [comment]
@mertemin I'm going to close this issue since it is not related to the gradle-jooq-plugin. If the suggestion by @lukaseder does not solve your problem, I suggest you open an issue or thread on the jOOQ side of things.
