### ISSUE TITLE
jOOQ requires gradle multi module when codegen with JPA Entity

### ISSUE THREAD

**Issue by SightStudio** [etiennestuder/gradle-jooq-plugin#427]
Question Summary)
Is There a way to use JPA entity based jOOQ codegen in Gradle Project without using multi module?

sorry for[ duplicate issue in jooq repository](https://github.com/jOOQ/jOOQ/issues/13824)

----
Hello, I'm tried to use jOOQ as a backup plan in project where JPA is mainly used. (also gradle is used)

So i created sample jOOQ project that

1. jOOQ DSL created by JPA entity 
(Which is reverse engineered by h2 database as documented)

2. project manged by gradle 

here's [the sample project](https://github.com/SightStudio/blog-code/tree/develop/jooq-codegen-with-entity) i created.
here's [codegen-jpa document ](https://www.jooq.org/doc/3.17/manual-single-page/#codegen-jpa)

| document  | my project |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/50672087/180944903-1bfe58a5-946c-4058-aa75-d9e706b1aef4.png) | ![image](https://user-images.githubusercontent.com/50672087/180946948-a1186528-e2b6-4288-8948-aad4122ad109.png) |

like picture above, it requires separated gradle module that contains jpa entity. 
this forced feature makes difficult applying jooq to exsisting project.

i think this is the problem that etiennestuder's gradle plugin is not offical part of jooq. (not certainty)
(same reason for creating jooq-custom module for JPrefixStrategy, i guess)

i found [similar example project with maven](https://github.com/jOOQ/jOOQ/tree/main/jOOQ-examples/jOOQ-jpa-example-entities). it works fine in same module. i hope gradle version would be easy like this

**Comment by lukaseder** [comment]
For the record, this question was also asked here:
https://github.com/jOOQ/jOOQ/issues/13824

And I've given a reply here:
https://github.com/jOOQ/jOOQ/issues/13824#issuecomment-1200128450

**Comment by SightStudio** [comment]
thanks for lukaseder, my curious solved. i'll close this issue.
