### ISSUE TITLE
Kotlin + jooq + flyway + spring + postgresql - getting SAX parser errors.

### ISSUE THREAD

**Issue by hadson172** [etiennestuder/gradle-jooq-plugin#431]
I setup jooq with kotlin, flyway, spring, postgresql using projects inside example directory. After run generateJooq I am getting the following warrning errors:

> 

> WARNING: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 921; cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeExcludePackageRoutines}'. O
> ne of '{"http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":properties, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":regexFlags, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeTables, "http://www.jooq.org/xsd/jooq-codeg
> en-3.14.0.xsd":includeEmbeddables, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeRoutines, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeTriggerRoutines, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includ
> ePackages, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includePackageRoutines, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includePackageUDTs, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includePackageConstants, "h
> ttp://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeUDTs, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeDomains, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeSequences, "http://www.jooq.org/xsd/jooq-codegen
> -3.14.0.xsd":includeIndexes, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includePrimaryKeys, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeUniqueKeys, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeForeign
> Keys, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeCheckConstraints, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeSystemIndexes, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeSystemCheckConstraints
> , "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":includeInvisibleColumns, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":recordVersionFields, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":recordTimestampFields, "http://www
> .jooq.org/xsd/jooq-codegen-3.14.0.xsd":syntheticObjects, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":syntheticIdentities, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":syntheticPrimaryKeys, "http://www.jooq.org/xsd/jooq-co
> degen-3.14.0.xsd":overridePrimaryKeys, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":dateAsTimestamp, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":ignoreProcedureReturnValues, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xs
> d":unsignedTypes, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":integerDisplayWidths, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":inputCatalog, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":outputCatalog, "http://www.j
> ooq.org/xsd/jooq-codegen-3.14.0.xsd":outputCatalogToDefault, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":inputSchema, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":outputSchema, "http://www.jooq.org/xsd/jooq-codegen-3.14.0
> .xsd":outputSchemaToDefault, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":catalogs, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":schemata, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":schemaVersionProvider, "http://ww
> w.jooq.org/xsd/jooq-codegen-3.14.0.xsd":catalogVersionProvider, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":orderProvider, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":embeddables, "http://www.jooq.org/xsd/jooq-codegen-3.
> 14.0.xsd":embeddablePrimaryKeys, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":embeddableUniqueKeys, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":embeddableDomains, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":customTy
> pes, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":enumTypes, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":forcedTypes, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":forceIntegerTypesOnZeroScaleDecimals, "http://www.joo
> q.org/xsd/jooq-codegen-3.14.0.xsd":tableValuedFunctions, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":logSlowQueriesAfterSeconds, "http://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd":logSlowResultsAfterSeconds}' is expected.      
> sie 05, 2022 1:28:44 PM org.jooq.tools.JooqLogger warn

I've added this line to budilscript:
`	configurations["classpath"].resolutionStrategy.eachDependency {
		if (requested.group == "org.jooq") {
			useVersion("3.16.1")
		}
	}`
	
And it still does not work. Any tips ?

**Comment by etiennestuder** [comment]
- https://github.com/etiennestuder/gradle-jooq-plugin#synchronizing-the-jooq-version-between-the-spring-boot-gradle-plugin-and-the-jooq-gradle-plugin
- https://github.com/etiennestuder/gradle-jooq-plugin#specifying-the-jooq-version-and-edition
- https://github.com/etiennestuder/gradle-jooq-plugin#enforcing-the-jooq-configuration-xml-schema-version

You might also want to run you rbuild with `--scan` and then investigate the depencies section to see what is going on.

**Comment by etiennestuder** [comment]
I provied some suggestions. Closing now.
