### ISSUE TITLE
How to disable generate/clean task manually?

### ISSUE THREAD

**Issue by dantesun** [etiennestuder/gradle-jooq-plugin#45]
How to keep the generated sources in Git repository and executing the task manually?

**Comment by dantesun** [comment]
I find my answer.
project.tasks.getByName('compileJava').dependsOn -= 'generateSampleJooqSchemaSource'
project.tasks.getByName('clean').dependsOn -= 'cleanGenerateSampleJooqSchemaSource'

**Comment by etiennestuder** [comment]
Yes, also described in this example build:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/remove_task_dependency/build.gradle#L41

**Comment by etiennestuder** [comment]
@dantesun As of v2.0.10, running the clean task does no longer implicitly remove any generated jOOQ sources.
