### ISSUE TITLE
"./gradlew clean" should remove files from generated source dirs

### ISSUE THREAD

**Issue by sindhuvyshaki** [etiennestuder/gradle-jooq-plugin#46]
`plugins {
    id 'nu.studer.jooq' version '2.0.6'
}`

Running `gradle clean build` removes "ALL" the source files in the corresponding source directory and not just the files in the designated generation package.
`target {
               packageName = 'com.xx.xx.model'
               directory = 'src/main/gen'
           }`

Since the package itself is provided, the clean task should only remove the generated files. Not the entire source folder.

**Comment by etiennestuder** [comment]
This is the intended behavior. I highly recommend you generate the sources into a folder `src/main/gen/jooq` or alike. Note that different tasks should not share output locations. As of the upcoming Gradle 4.0, you will actually get a warning from Gradle if two tasks share the same output.

**Comment by etiennestuder** [comment]
@sindhuvyshaki As of v2.0.10, running the clean task does no longer implicitly remove any generated jOOQ sources.
