### ISSUE TITLE
jOOQ config error with com.android.library plugin

### ISSUE THREAD

**Issue by derabbink** [etiennestuder/gradle-jooq-plugin#47]
I have a similar issue to #4 - as far as the symptoms go. However, in my case it seems to go wrong whenever I use the `com.android.library` plugin instead of the `java` plugin.
**My jOOQ configuration then fails to work with `sourceSets.main`. How can I fix that?**

My jOOQ configuration `accounts(sourceSets.main)` fails with the following error:
```
$ ./gradlew generateAccountsJooqSchemaSource -i
[...]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/maarten/projects/android-app/data/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating project ':data'.
> Could not get unknown property 'main' for SourceSet container of type org.gradle.api.internal.tasks.DefaultSourceSetContainer.
```

Since any android module also has the option to configure `android.sourceSets`, I also tried plugging that into my jOOQ configuration `accounts(android.sourceSets.main)`
```
$ ./gradlew generateAccountsJooqSchemaSource -i
[...]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/maarten/projects/android-app/data/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating project ':data'.
> Could not find method accounts() for arguments [source set main, build_d5novax2tyffqw6yv97530w4h$_run_closure5$_closure8@269966ac] on object of type nu.studer.gradle.jooq.JooqExtension.
```

Below is my gradle file. It declares an android library module, and it throws in flyway, followed by jOOQ code generation. I'm using jOOQ 3.6.4, since that was the latest one I could find that works well with Java 7
```
apply plugin: 'com.android.library'
apply plugin: 'org.flywaydb.flyway'
apply plugin: 'nu.studer.jooq'

buildscript {
    dependencies {
        classpath 'org.xerial:sqlite-jdbc:3.18.0'
        classpath 'org.flywaydb:flyway-gradle-plugin:4.2.0'
        classpath 'nu.studer:gradle-jooq-plugin:2.0.6'
    }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    jooqRuntime 'org.xerial:sqlite-jdbc:3.18.0'
    compile 'org.flywaydb:flyway-core:4.2.0'
    compile 'org.jooq:jooq:3.6.4' // newest version compatible with Java 1.7
    compile 'org.sqldroid:sqldroid:1.0.3'
    testCompile 'junit:junit:4.12'
}

// Xerial SQLite does not create folders for DB files
task dbFolderCreate {
    doLast {
        new File("${projectDir}/build/tmp/").mkdirs()
    }
}

flyway {
    driver = 'org.sqlite.JDBC'
    url = "jdbc:sqlite:${projectDir}/build/tmp/gradle.db"
    locations = ["filesystem:${projectDir}/src/main/resources/sql/accounts"]
}

jooq {
    version = '3.6.4'
    edition = 'OSS'
    accounts(sourceSets.main) { // this is line 46
        jdbc {
            driver = 'org.sqlite.JDBC'
            url = "jdbc:sqlite:${projectDir}/build/tmp/gradle.db"
        }
        generator {
            name = 'org.jooq.util.DefaultGenerator'
            strategy {
                name = 'org.jooq.util.DefaultGeneratorStrategy'
            }
            database {
                name = 'org.jooq.util.sqlite.SQLiteDatabase'
                excludes = 'schema_version' // flyway tables
            }
            generate {
                deprecated = false
                records = false
                pojos = true

            }
            target {
                packageName = 'com.abbink.androidapp.data.jooq'
                directory = 'src/generated/java'
            }
        }
    }
}

flywayMigrate.dependsOn dbFolderCreate
generateAccountsJooqSchemaSource.dependsOn flywayMigrate
test.dependsOn flywayClean
```

**Comment by etiennestuder** [comment]
Thanks for the report. Unfortunately, I will not be able to look into this issue over the coming weeks due to my current work load. Maybe @oehme spots something at a glance.

**Comment by oehme** [comment]
> My jOOQ configuration then fails to work with sourceSets.main. How can I fix that?

The Android plugin does not use Gradle's `SourceSet` abstraction, but has its own AP. The jooq plugin does not support the Android SourceSet API at this point.

I propose we turn this into a feature request.

**Comment by derabbink** [comment]
Thank you for considering this. Making this a feature request seems like a good idea.

For now, I'll try to isolate my jOOQ-generated code into a traditional (non-android) `'java'` module, which I'll then use as a dependency in another `'com.android.library'` module.

**Comment by etiennestuder** [comment]
That sounds like a good approach, @derabbink.

**Comment by etiennestuder** [comment]
I'm going to close this issue since I will have no time in the near future to make significant changes to the reported issue. The workaround taken by @derabbink is very feasible and even goes towards more, smaller modules which helps with build time, too.
