### ISSUE TITLE
Cannot disable spatialTypes

### ISSUE THREAD

**Issue by whisper-bye** [etiennestuder/gradle-jooq-plugin#474]
> Invalid property: 'spatialTypes' on extension 'jooq.main.generationTool.generator.generate', value: false. Please check the current XSD: https://www.jooq.org/xsd/jooq-codegen-3.16.0.xsd.

jooq {
    version = '3.17.3'
    edition = JooqEdition.OSS
}

generate {
    spatialTypes = false
    fluentSetters = true
}

**Comment by etiennestuder** [comment]
- https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#specifying-the-jooq-version-and-edition
- https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#enforcing-the-jooq-configuration-xml-schema-version
