### ISSUE TITLE
plugin seems to be using its own version of jOOQ instead of provided

### ISSUE THREAD

**Issue by cmrgKoradir** [etiennestuder/gradle-jooq-plugin#478]
I've been trying to use the jOOQ trial version to make use of audit columns.
In order to be able to configure audit columns, `org.jooq.meta.jaxb` needs be of version 3.17+
but during configuration of the plugin, it's still of version `3.16.4`.

I managed to enforce `3.17.3` by using a build script,
```kotlin
buildscript {
    configurations["classpath"].resolutionStrategy.eachDependency {
        if (requested.group == "org.jooq") {
            useVersion("3.17.3")
        }
    }
}
```

but the plugin seems to internally pull the open-source version because I get 
```
java.lang.UnsupportedClassVersionError: org/jooq/meta/jaxb/Configuration has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
whereas the jOOQ trial is java-8 compliant (and the commercial license provides a java-11 compliant version, which is what we would want for our actual project).

This is possibly related to https://github.com/etiennestuder/gradle-jooq-plugin/issues/183, but unfortunately the workaround posted therein

```kotlin
dependencies {
    api("$jooqGroup:jooq:$jooqVersion")
    implementation("$jooqGroup:jooq-codegen:$jooqVersion")
    implementation("$jooqGroup:jooq-meta:$jooqVersion")
    jooqGenerator("org.postgresql:postgresql:42.4.2")
    runtimeOnly("org.postgresql:postgresql:42.4.2")

    modules {
        module("org.jooq:jooq") {
            replacedBy("$jooqGroup:jooq", "nu.studer.jooq bugfix #183") // https://github.com/etiennestuder/gradle-jooq-plugin/issues/183
        }
    }
}
```
doesn't seem to have any effect.

cf. https://stackoverflow.com/questions/73522248/how-do-you-set-up-jooq-audit-columns-in-the-gradle-plugin/73524998 for full gradle files and further information

**Comment by apatrida** [comment]
I'm hitting same problem, and can resolve it in part of the project but not all.

**Comment by etiennestuder** [comment]
See the conversation on [this issue](https://github.com/etiennestuder/gradle-jooq-plugin/issues/640).
