### ISSUE TITLE
How to configure multiple schema ?

### ISSUE THREAD

**Issue by MoraxMa** [etiennestuder/gradle-jooq-plugin#482]
I found it in jooq's document

https://www.jooq.org/doc/latest/manual-single-page/#codegen-database-catalog-and-schema-mapping
![image](https://user-images.githubusercontent.com/44521439/188544224-b6c88e4c-ed6e-4fe6-891d-7d5d183ee66a.png)

But I can't use it

![image](https://user-images.githubusercontent.com/44521439/188545381-efdd5f88-eeb3-417c-bcee-f59e19599074.png)

**Comment by nstrong-scw** [comment]
thank you @luchooo87 , and you don't even need the generator function:

```
// ...
schemata = listOf("schema_1","schema_2").map { SchemaMappingType().apply { inputSchema = it } }
// ...
```

**Comment by etiennestuder** [comment]
This question came up before when you search the closed GH issues. I'm not a jOOQ domain expert. Thus, I cannot help you in this case how to best configure jOOQ. I hope for your understanding.
