### ISSUE TITLE
Invalid content was found starting with element 'matchers'

### ISSUE THREAD

**Issue by yissachar** [etiennestuder/gradle-jooq-plugin#50]
I'm trying to configure the JOOQ generator to use camel-case for the generated POJOs. Using https://www.jooq.org/doc/3.9/manual/code-generation/codegen-matcherstrategy/ as a guide I've tried using the following syntax:

```
generator {
    name = 'org.jooq.util.DefaultGenerator'

    strategy {
        name = 'org.jooq.util.DefaultGeneratorStrategy'
        matchers {
            tables {
                table {
                    tableClass {
                        transform = "CAMEL"
                    }
                }
            }
        }
    }
 }
```

But I get the following exception:

> javax.xml.bind.MarshalException
>   - with linked exception:
>  [org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-complex-type.2.4.d: Invalid content was found starting with element 'matchers'. No child element is expected at this point.]

Am I going about this the wrong way? Or is it not supported in this plugin?

**Comment by lukaseder** [comment]
[The specification for the `Strategy` type](https://www.jooq.org/xsd/jooq-codegen-3.9.2.xsd) specifies:

```xml
<complexType name="Strategy">
  <choice>
    <element name="name" type="string" minOccurs="0" maxOccurs="1" default="org.jooq.util.DefaultGeneratorStrategy"/>
    <element name="matchers" type="tns:Matchers" minOccurs="0" maxOccurs="1"/>
  </choice>
</complexType>
```

The choice here means that you must pick either `name` or `matchers`, but not both. That's what the exception tries to say.

So, simply remove the `name` specification.

**Comment by yissachar** [comment]
@lukaseder I get the same error when I remove `name`.

**Comment by yissachar** [comment]
For completeness, here is my entire config after removing `name`:

```
jooq {
    version = '3.9.3'

    myThing(sourceSets.main) {
        jdbc {
            driver = 'org.postgresql.Driver'
            url = 'jdbc:postgresql://localhost:5432/test'
            user = 'abc'
            password = ''
        }

        generator {
            name = 'org.jooq.util.DefaultGenerator'

            strategy {
                matchers {
                    tables {
                        table {
                            tableClass {
                                transform = "CAMEL"
                            }
                        }
                    }
                }
            }

            database {
                name = 'org.jooq.util.postgres.PostgresDatabase'
                inputSchema = 'public'
            }

            generate {
                relations = true
                deprecated = false
                records = true
                pojos = true
                immutablePojos = false
                fluentSetters = false
            }

            target {
                packageName = 'com.me.mine'
            }

        }
    }
}
```

The error is the same as in my first post.

**Comment by lukaseder** [comment]
Interesting, this looks correct to me now. Any ideas, @etiennestuder ?

Note, if this is blocking you right now: A workaround is, of course, to use a programmatic strategy as documented here:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy

**Comment by etiennestuder** [comment]
@yissachar @lukaseder You ran into the issue explained here:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#defining-matchers

**Comment by lukaseder** [comment]
Oh, true, I forgot about that. Thanks for the pointer and for documenting this

**Comment by yissachar** [comment]
Thanks, can't believe I missed that!
