### ISSUE TITLE
A minimal example of adding prefixes to the generated records

### ISSUE THREAD

**Issue by czyzby** [etiennestuder/gradle-jooq-plugin#51]
The generated POJOs and classes representing tables have the same class name, which is tedious when you need to use both. Could you post a minimal example of how to add prefix or suffix to the generated table classes?

**Comment by lukaseder** [comment]
There are two ways to specify a generator strategy in the jOOQ code generator:

- Programmatic: https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy
- Configuratively: https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy

This plugin has a short section illustrating how to specify a matcher configuratively:
https://github.com/etiennestuder/gradle-jooq-plugin#defining-matchers

**Comment by czyzby** [comment]
Thanks, now I feel silly I missed that. For the record, this is what I used to add suffix to all generated tables:

```Groovy
strategy {
	name = null
	matchers {
		tables {
			table {
				// Adding "Table" suffix to generated record classes:
				tableClass {
					transform = 'PASCAL'
					expression = '$0_table'
				}
			}
		}
		fields {
			field {
				// Generating record fields with CamelCase:
				fieldIdentifier {
					transform = 'CAMEL'
					expression = '$0'
				}
			}
		}
	}
}
```
