### ISSUE TITLE
clean task is too agressive

### ISSUE THREAD

**Issue by iceback** [etiennestuder/gradle-jooq-plugin#52]
I would prefer that only the named package got deleted by 'gradle clean'.  I had non-generated but related code (extensions which wrap dependent tables and such) in a directory parallel with the top package.
My config had target {dir = src/jooq/java; package = edu.uni.lab.db.generated} with my extensions in edu.uni.lab.db.crafted.
I have since moved that package to another sourceset but I feel it's now misplaced.

**Comment by etiennestuder** [comment]
I'm sorry @iceback, but this is not going to change the gradle-jooq-plugin. Shared output directories are a no-go in Gradle that leads to all sorts of issues.

**Comment by lukaseder** [comment]
Interesting, is there a resource that documents this and the trouble that could be arising from this?

**Comment by etiennestuder** [comment]
@lukaseder See [here](https://guides.gradle.org/using-build-cache/#concepts_overlapping_outputs).

**Comment by etiennestuder** [comment]
@iceback As of v2.0.10, running the clean task does no longer implicitly remove any generated jOOQ sources.
