### ISSUE TITLE
jooq task dependency

### ISSUE THREAD

**Issue by iceback** [etiennestuder/gradle-jooq-plugin#53]
I would like to compile a single class, an Annotator, before running the code generator. I tried 'jooq (dependsOn: annoTask)' and 'jooq{doFirst(annoTask)}' but neither parses. Is there a way to make jooq dependent on some other part of the build.
Currently I have the class in a separate jar but that seems over kill.

**Comment by felipefzdz** [comment]
Hi @iceback.

`jooq` is the DSL extension point where you can pass info into `generateSampleJooqSchemaSource` task. So, if you want to establish some order dependency between tasks, you need to refer to the task, not to the extension point. Something like this:

```
generateSampleJooqSchemaSource.dependsOn annoTask
```

**Comment by etiennestuder** [comment]
@iceback There is also an [example project](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/use_custom_generator) that shows how to first build some classes that are then used in the jooq configuration.
