### ISSUE TITLE
smart code generation

### ISSUE THREAD

**Issue by jottyfan** [etiennestuder/gradle-jooq-plugin#59]
In my project, I want to have the generated jooq classes in a sub package. If I don't specify `directory`, the generated classes are NOT put to `src/main/java` (as documented). But if I specify `src/main/java`, all my other packages and classes are removed from that folder. How can I forbid your plugin to delete the complete folder and just only delete all files under `packageName`(which is in fact a folder in the file system)?

```gradle
jooq {
  myverydb(sourceSets.main) {
    generator {
      target {
        packageName = 'my.very.own.package.db.jooq'
        directory = 'src/main/java'
      }
    }
  }
}
```
My package structure is like that (all in `src/main/java`):
```java
my.very.own.package.control
my.very.own.package.db.gateway
my.very.own.package.db.jooq
my.very.own.package.model
```

**Comment by etiennestuder** [comment]
> If I don't specify directory, the generated classes are NOT put to src/main/java (as documented). 

Not sure why you say that. This is not what is written in the docs. The docs are correctly saying:

```By default, the generated sources are written to `build/generated-src/jooq/<configurationName>`. The
output directory can be configured by explicitly setting the `directory` attribute of the `target` configuration.```

You should point to a different directory than src/main/java given the Compile task already writes into that directory. In Gradle, sharing an output directory between different tasks should not be done.

**Comment by etiennestuder** [comment]
See also https://github.com/etiennestuder/gradle-jooq-plugin/issues/52

**Comment by jottyfan** [comment]
That's bad news. The maven plugin of jooq is able to write to src/main/java without deleting all the other packages, why is the gradle plugin so restrictive in that? Or is there a better way to achieve my demands? In fact, I want two independent tasks for my project: one to generate the jooq classes and one to build the war file. See my gradle file for details and have a look at the project, maybe that is better than an academical example:

https://github.com/jottyfan/CampOrganizer/blob/master/build.gradle

and

https://github.com/jottyfan/CampOrganizer/blob/c60703b24ec15d69ae47646c7b07655b174f4ab7/pom.xml

for comparison to maven. I know I could use the https://www.jooq.org/doc/3.7/manual/code-generation/codegen-gradle/#N35226 MarkupBuilder, but I'd like to use your plugin if it is able to do the job I want. Any ideas?

**Comment by etiennestuder** [comment]
> That's bad news. The maven plugin of jooq is able to write to src/main/java without deleting all the other packages, why is the gradle plugin so restrictive in that?

Not sharing output directories is not plugin related. See this [link](https://guides.gradle.org/using-build-cache/#concepts_overlapping_outputs) that I had posted.

In this specific case here, mixing source files under version control with generated resources under the same source tree I would consider a pretty bad practice.
.
> In fact, I want two independent tasks for my project: one to generate the jooq classes and one to build the war file.

All the gradle jooq plugin does is generate the sources into a given folder and wiring them into the java source code compilation. From there on, you can do with the classes as you wish: package them, run tests against them, etc.

**Comment by jottyfan** [comment]
> In this specific case here, mixing source files under version control with generated resources under the same source tree I would consider a pretty bad practice.
One might consider this bad practice, but for such a small project, an own library for database generated classes is an overkill. Putting the generated classes to a different source folder might work, but I wonder why maven is able to solve this out of the box and jooq design seems to be in the way to find such an easy solution.

> All the gradle jooq plugin does is generate the sources into a given folder and wiring them into the java source code compilation.
Mostly true, but you did not mention that the gradle jooq plugin deletes the files in the source folder completely on rebuild - and exactly this is the problem here. Why can the folder that is cleared not be the one from the packageName? Then, this problem would be gone.

**Comment by lukaseder** [comment]
> One might consider this bad practice, but for such a small project, an own library for database generated classes is an overkill. 

Curious: Why? I'm not a Gradle expert, but I could imagine there exists a tool similar to the maven-shade-plugin, using which you could merge the library for database generated classes into its consumer again.

**Comment by etiennestuder** [comment]
> One might consider this bad practice, but for such a small project, an own library for database generated classes is an overkill. Putting the generated classes to a different source folder might work, but I wonder why maven is able to solve this out of the box and jooq design seems to be in the way to find such an easy solution.

I did not say to create a separate library. Just generate the sources to a different directory within the same module. A source set can contain multiple directories in Gradle. The gradle jooq plugin will add the directory to the source set of your choice, typically `main`.

The behavior you observe has nothing to do with jOOQ per se.

> Mostly true, but you did not mention that the gradle jooq plugin deletes the files in the source folder completely on rebuild.

By `rebuild`, do you mean calling `clean`? The jooq plugin adds a task dependency to clean the output of the jooq task when `clean` is run. Since you point to src/main/java, this folder gets deleted upon `clean`.

If you want to call `clean` but still not clean everything (which would be quite bad IMO), then remove that task dependency. Or just generate to a different folder like mentioned above and all your problems are gone - and you even get to benefit from incremental build feature and build cache feature which you cannot otherwise.

**Comment by jottyfan** [comment]
> Or just generate to a different folder like mentioned above and all your problems are gone - and you even get to benefit from incremental build feature and build cache feature which you cannot otherwise.

Yes, sometimes it is important to think twice. I suppose you're right with a separate source folder, this will be a bit strange for me, but I will assimilate that :)

Thanks for the discussion, I see my issue solved now.

**Comment by etiennestuder** [comment]
Great to hear!

**Comment by etiennestuder** [comment]
@jottyfan As of v2.0.10, running the `clean` task does no longer implicitly remove any generated jOOQ sources.

**Comment by tkruse** [comment]
@etiennestuder It seems that plugin version 9.x may delete the target.directory again, not using the package. The code causing this is:
```
        fileSystemOperations.delete(spec -> spec.delete(outputDir.get()));
```
in https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/src/main/groovy/nu/studer/gradle/jooq/JooqGenerate.java

While I agree it is dodgy to add generated files into the same root folder as non-generated, this can happen to any team, and this plugins behavior can destroy hours of work, which is also not great style.
