### ISSUE TITLE
Expose `kotlinNotNull*` configuration properties for Kotlin Codegen with jOOQ 3.18 support

### ISSUE THREAD

**Issue by michael-delafontaine-TR** [etiennestuder/gradle-jooq-plugin#595]
First off, thank you for supporting the JOOQ `3.17.6.` with the 8.1 release :) 

There's a new configuration property that newer versions of JOOQ support for Kotlin code generation, in particular, the support of generating Kotlin non-nullable types in generated JOOQ Kotlin code: https://github.com/jOOQ/jOOQ/issues/10212#issuecomment-1252351193

It would be brilliant if these properties would be exposed in `gradle-jooq-plugin`

**Comment by etiennestuder** [comment]
My understanding is that these properties will be available in jOOQ 3.18 which has not yet been released. Once it is released, you can configure the gradle-jooq-plugin to use the 3.18 version of jOOQ and you should have would you need.

**Comment by apatrida** [comment]
Is this true even in Gradle build files using Kotlin Script?  It picks up the new configuration elements directly?  (using classes instead of some dynamic JSONB magic)

**Comment by strindberg** [comment]
As far as I can tell this works already. I used the preview of jOOQ 3.18 (3.18.0-SNAPSHOT) and the Kotlin Script version of gradle, and this works as expected:

```kotlin
            jooqConfiguration.apply {
                generator.apply {
                    name = "org.jooq.codegen.KotlinGenerator"
                    generate.apply {
                        isKotlinNotNullRecordAttributes = true
                    }
                   ...
```

**Comment by thomasneuteboom** [comment]
@strindberg I can't seem to get this working. Even with explicitly setting the version to 3.18.0. Can you please elaborate? :) 

```
jooq {
    version.set("3.18.0") 

    configurations {
        create("main") {  
            jooqConfiguration.apply {
                logging = Logging.DEBUG
                jdbc.apply {
                    driver = "org.postgresql.Driver"
                    url = "jdbc:postgresql://127.0.0.1:5432/database"
                    user = "user"
                    password = "secret"
                }
                generator.apply {
                    name = "org.jooq.codegen.KotlinGenerator"
                    database.apply {
                        name = "org.jooq.meta.postgres.PostgresDatabase"
                        inputSchema = "public"
                    }
                    generate.apply {
                        // Working
                        isImplicitJoinPathsAsKotlinProperties = true
                        // Working
                        isKotlinSetterJvmNameAnnotationsOnIsPrefix = true
                        // Working
                        isPojosAsKotlinDataClasses = true

                        // Not working
                        isKotlinNotNullPojoAttributes = true
                        // Not working
                        isKotlinNotNullRecordAttributes = true
                        // Not working
                        isKotlinNotNullInterfaceAttributes = true
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}
```

**Comment by etiennestuder** [comment]
> Is this true even in Gradle build files using Kotlin Script? It picks up the new configuration elements directly? (using classes instead of some dynamic JSONB magic)

@apatrida See here:
- https://github.com/etiennestuder/gradle-jooq-plugin#gradle-kotlin-dsl-2 AND
- https://github.com/etiennestuder/gradle-jooq-plugin#gradle-kotlin-dsl-3
- https://github.com/etiennestuder/gradle-jooq-plugin#working-with-configurations-in-the-kotlin-dsl

**Comment by etiennestuder** [comment]
> @strindberg I can't seem to get this working. Even with explicitly setting the version to 3.18.0. Can you please elaborate? :)

@strindberg See here:
- https://github.com/etiennestuder/gradle-jooq-plugin#specifying-the-jooq-version-and-edition AND
- https://github.com/etiennestuder/gradle-jooq-plugin#enforcing-the-jooq-configuration-xml-schema-version AND
- https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/example/specify_jooq_config_xml_schema_version/build.gradle

**Comment by thomasneuteboom** [comment]
Thanks! 🙏🏼

**Comment by enif-lee** [comment]
```kts
// in build.gradle.kts
buildscript {
    configurations["classpath"].resolutionStrategy.eachDependency {
        if (requested.group == "org.jooq") {
            useVersion("3.18.0")
        }
    }
}

jooq {
    version.set("3.18.0")
    configurations {
      // .. configure options
    }
}
```
still not going well.. 🤔 

![image](https://user-images.githubusercontent.com/9916002/225893341-717f6752-535e-4070-adb3-d9b75a8a93e8.png)

**Comment by mikehearn** [comment]
jOOQ 3.18 is now out!

**Comment by etiennestuder** [comment]
I'll close this issue since the plugin already supports using a different jOOQ version than what it was built with itself.

I explained this in the thread:
- https://github.com/etiennestuder/gradle-jooq-plugin/issues/595#issuecomment-1466355751
- https://github.com/etiennestuder/gradle-jooq-plugin/issues/595#issuecomment-1466360847
