### ISSUE TITLE
Wrongly set task output 

### ISSUE THREAD

**Issue by wstrzalka** [etiennestuder/gradle-jooq-plugin#6]
Having the following configuration:
            ................
            target {
                packageName = 'foo.bar.jooq.generated'
                directory = 'src/main/java'
            }
            .................
task output as set by the plugin is set with the 'directory' variable only to 'src/main/java' instead of full package path: 'src/main/java/foo/bar/jooq/generated'.

The consequence is that rule generated clean<...> task clear all the project sources :)

**Comment by etiennestuder** [comment]
Thanks for the feedback. I will look into it.

**Comment by oehme** [comment]
You should not generate to src/main/java, but to a generated source folder. This plugin already auto-configures this to a folder below the build folder.

**Comment by etiennestuder** [comment]
I understand what you are saying, @wstrzalka. I suggest you generate the sources into a distinct folder that is not shared with any other tasks' outputs. The clean<...> task approach will then work.
