### ISSUE TITLE
a sample with seperate jooq generate task?

### ISSUE THREAD

**Issue by gillbates** [etiennestuder/gradle-jooq-plugin#603]
Hi @etiennestuder 

thx for all the efforts.
As the doc is a little bit of hard for gradle new users ... I wonder if you could provide a sample jooq.gradle and it could be executed only manually? 
I have copied the sample and it will break the compile process on our CI as our CI cannot connect to our DB.
So I wonder if we could have something documented to use this plugin only manually?
thanks in advance!

**Comment by etiennestuder** [comment]
See [this](https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/example/configure_task_dependencies/build.gradle#L18) example.

**Comment by gillbates** [comment]
> See [this](https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/example/configure_task_dependencies/build.gradle#L18) example.

well done, thx @etiennestuder !
