### ISSUE TITLE
Different Jooq Sources for Same Target - Kotlin DSL

### ISSUE THREAD

**Issue by austinarbor-wk** [etiennestuder/gradle-jooq-plugin#613]
Hello,
Can you please provide the equivalent kotlin dsl syntax for [this](https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/example/configure_different_jooq_sources_for_same_target_source_set/build.gradle#L65-L68) ? I can't figure out how to correctly access the `outputDir` variable.

Thanks

**Comment by etiennestuder** [comment]
Please ask in the [Gradle forum ](https://discuss.gradle.org/)for Gradle Kotlin DSL-specific questions.
