### ISSUE TITLE
RFC: Gradle jooq plugin for kotlin-dsl

### ISSUE THREAD

**Issue by rohanprabhu** [etiennestuder/gradle-jooq-plugin#62]
Did not intend to create an issue, but this seems to be the only way to communicate with authors. I had some trouble using this plugin with the kotlin-dsl, and also noticed an issue that was closed in this repo mentioning similar troubles. For those reasons, I have created a plugin for kotlin-dsl: https://github.com/rohanprabhu/kotlin-dsl-gradle-jooq-plugin that allows type-safe usage.

The reason I am posting this here is because I drew massive inspiration from this plugin, and I have kept most of the concepts similar, in terms that we have tried to emulate the style as much as possible of this plugin. I have credited the same in the README and would like your comments on the same.

And when I say "massive inspiration", I pretty much learnt how to write a gradle plugin reading your code :)

Regards,
rohan

**Comment by lukaseder** [comment]
This could be a really nice contribution to the gradle-jooq-plugin. @etiennestuder, what are your thoughts for the future of your plugin, given that Gradle and Kotlin have become [better friends](https://blog.gradle.org/kotlin-meets-gradle) over the recent years?

**Comment by etiennestuder** [comment]
@lukaseder Not sure what you mean by _contribution to the gradle-jooq-plugin_. Can you elaborate?

**Comment by lukaseder** [comment]
Well:

1. No one wants to support / maintain two Gradle plugins :-)
2. Apparently, your plugin doesn't work in some Kotlin related use-case (which I have not yet further verified) *"while using kotlin-dsl it can get very difficult to use it because it employs the dynamic method mechanism of groovy, which the kotlin runtime cannot use to figure out the types and most of the types have to be annotated by the developer"*

**Comment by etiennestuder** [comment]
Gradle Kotlin DSL has not reached 1.0 yet (it is close though). I do not intend to focus on Kotlin support in the gradle-jooq-plugin until Gradle Kotlin DSL 1.0 is released. Also, once we remove the dynamic dispatching from the gradle-jooq-plugin, the biggest obstacle for Kotlin is removed, the rest is very little work. Note that the dynamic dispatching allows for very little code to support the full jooq xsd and in different versions, at the price of being tied to Groovy.

@rohanprabhu I'm glad you got to learn about Gradle plugin development :-) What I believe would be most valuable as a first step for the existing gradle-jooq-plugin users is if you would come up with a pull request that replaces the dynamic dispatching with the static counter-part based on the current xsd. Traversing the Configuration object at build time and generating a code structure that best matches Gradle's DSL implementation style is how I would approach it.

**Comment by olivierlemasle** [comment]
@etiennestuder Does that mean that in a version where dynamic dispatching has been replaced by a static DSL generated from XSD, the Gradle plugin will be tied to a specific jOOQ version?

**Comment by etiennestuder** [comment]
@olivierlemasle I don't see any other way. Either it is dynamic and can deal with APIs not present at the time of a given gradle jooq plugin release, or it is static and can only deal with the APIs known at that time.

**Comment by davinkevin** [comment]
Any news about this one? Very interested about kotlin dsl compatible system wiht gradle to use our favorite SQL lib !

**Comment by martintreurnicht** [comment]
https://github.com/etiennestuder/gradle-jooq-plugin/pull/91

**Comment by XhstormR** [comment]
Is there an update?

**Comment by zeveras** [comment]
Any news about kotlin dsl support?

**Comment by etiennestuder** [comment]
I've come to the decision that I will not make the support of the Kotlin DSL a first-class feature of the gradle-jooq-plugin. I've explained my reasons [here](https://github.com/etiennestuder/gradle-jooq-plugin/pull/91#issuecomment-513384444).

You have the following options with the gradle-jooq-plugin:

1. Use @martintreurnicht's approach of including a single Kotlin class in your project's buildSrc, as demonstrated [here](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/use_kotlin_dsl).
1. Use the Kotlin DSL for your main build scripts but configure the jOOQ code configuration in a Groovy script and have it included via `apply(from = "useJooq.gradle")` from your Kotlin scripts.

**Comment by etiennestuder** [comment]
As of 5.x, the gradle-jooq-plugin supports the Gradle Kotlin DSL as a first-class citizen. See the README file:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md

See this complete example written with the Gradle Kotlin DSL:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts

**Comment by lukaseder** [comment]
For anyone interested, jOOQ 3.19 will publish a new `jOOQ-meta-kotlin` module, where all the JAXB-generated `jOOQ-meta` types get some auxiliary kotlin DSL API for more idiomatic construction:
https://github.com/jOOQ/jOOQ/tree/main/jOOQ-meta-kotlin

The extensions there contain things like:

```kotlin
fun Jdbc.properties(block: MutableList<Property>.() -> Unit) {
    block(properties)
}

@JvmName("mutableListProperty")
fun MutableList<Property>.property(block: Property.() -> Unit) {
    val e = Property()
    block(e)
    add(e)
}
```

So now, you can simply write:

```kotlin
jdbc {
    properties {
        property {
            key = "key"
            value = "value"
        }
    }
}
```

With auto completion, etc. The module will be maintained automatically, in the future, so it will always be up to date with the latest new `jOOQ-meta` types.

While it's obviously possible to continue using the approach currently recommended here:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_kotlin_dsl/build.gradle.kts (with things like `listOf()` and `Property().apply { ...`, I feel the DSL approach is a bit nicer?

This plugin here could add a dependency, so the functions will be available automatically as soon as this import is added:

```kotlin
import org.jooq.meta.kotlin.*
```

**Comment by etiennestuder** [comment]
> I feel the DSL approach is a bit nicer?

Definitely. The DSL will be on par with the Groovy DSL. I will include that dependency.

**Comment by etiennestuder** [comment]
@rohanprabhu  @davinkevin  The gradle-jooq-plugin v10.1 comes with first-class support for the Gradle Kotlin DSL.
https://github.com/etiennestuder/gradle-jooq-plugin/releases/tag/v10.1

It relies on Lukas's `jooq-meta-kotlin` library.
The only thing required in the user's build file is the declaration of `import org.jooq.meta.kotlin.*`
