### ISSUE TITLE
Register tasks for use in kotlin dsl

### ISSUE THREAD

**Issue by strindberg** [etiennestuder/gradle-jooq-plugin#621]
I don't know enough of gradle internals to know exactly what is missing, but it seems that many other gradle plugins register their tasks in a way that makes them immediately accessible in a build.gradle.kts file.

In this example:
```kotlin
tasks.named("generateJooq") {
    dependsOn(tasks.flywayMigrate)
}
```

`tasks.flywayMigrate` is accessible (including IDE completion suggestions), but the the jooq task "generateJooq" must be found dynamically with a string.

It would be nice if the jOOQ tasks were registered by the plugin so that the following code would work:

```kotlin
tasks.generateJooq {
    dependsOn(tasks.flywayMigrate)
}
```

**Comment by etiennestuder** [comment]
The `generateJooq` task is created dynamically based on the jOOQ configuration block (note that the task name is derived from whatever naming you use in the configuration). I assume this is why the IDE does not know about it upfront, but I cannot say for sure.

The way you are referring to tasks (`tasks.flywayMigrate`) is not recommended. It forces early task instantiation and configuration. Instead, you should use the Gradle APIs that are compatible with task avoidance configuration:
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

This is not specific to the jOOQ plugin but to Gradle builds / tasks in general.

**Comment by strindberg** [comment]
Thanks for the explanation. If the jooq tasks are dynamically registered, I can see why they can not be referenced directly. 

But to be sure, is the reference to `tasks.flywayMigrate` really unwise? It is a reference to `TaskProvider<FlywayMigrateTask>`, which, if I read the documentation correctly, does provide lazy instantiation of the task and thus configuration avoidance.

**Comment by etiennestuder** [comment]
With the Groovy DSL, `tasks.foo` is equivalent to TaskContainer.findByPath(String), configuring the task eagerly, regardless of how the task was originally registered. With the Kotlin DSL, the behavior is different. So, it depends on what DSL you use.
