### ISSUE TITLE
Functionality for includeExcludeColumns 

### ISSUE THREAD

**Issue by wenzhao91** [etiennestuder/gradle-jooq-plugin#629]
Currently the flag for includeExcludeColumns is not present. Without it, the excludes regex does not excludes columns

https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-includes-excludes/

**Comment by etiennestuder** [comment]
The following example works:

```jooq {
    configurations {
        main {
            generationTool {
                jdbc {
                    driver = 'org.h2.Driver'
                    url = 'jdbc:h2:~/test;AUTO_SERVER=TRUE'
                    user = 'sa'
                    password = ''
                }
                generator {
                    name = 'org.jooq.codegen.DefaultGenerator'
                    database {
                        name = 'org.jooq.meta.h2.H2Database'
                        regexFlags = [org.jooq.meta.jaxb.RegexFlag.COMMENTS,org.jooq.meta.jaxb.RegexFlag.MULTILINE]
                        includes = '.*'
                        excludes = '.*'
                    }
                }
            }
        }
    }
}

**Comment by wenzhao91** [comment]
I'm using kotlin, i'm trying to exclude jooq from generating columns that are named **inserted_at** and I tried following your example but it's not working. The generated records still contain the column **inserted_at** :

jooq {
    configurations {
        create("main") {  // name
            generateSchemaSourceOnCompilation.set(true)  // default (can be omitted)// of the jOOQ configuration
            jooqConfiguration.apply {
                logging = Logging.WARN
                jdbc.apply {
                    driver = "org.postgresql.Driver"
                    url = "jdbc:postgresql://localhost:1234/database"
                    user = "user"
                    password = "password"
                }
                generator.apply {
                    name = "org.jooq.codegen.DefaultGenerator"
                    database.apply {
                        name = "org.jooq.meta.postgres.PostgresDatabase"
                        inputSchema = "card"
                        regexFlags.add(org.jooq.meta.jaxb.RegexFlag.COMMENTS)
                        regexFlags.add(org.jooq.meta.jaxb.RegexFlag.MULTILINE)
                        includes = ".*"
                        excludes = "inserted_at"

                    }
                    generate.apply {
                        isDeprecated = false
                        isRecords = true
                        isImmutablePojos = true
                        isFluentSetters = true
                    }
                    target.apply {
                        packageName = "com.example.jooq"
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}

**Comment by etiennestuder** [comment]
I cannot help you with the jOOQ specifics, only with the gradle-jooq-plugin configuration. You need to ask @lukaseder about the jOOQ specific.

I suggest you look at the file under `build/tmp/generateJooq/config.xml` and include that in your report / question against the jOOQ repository.
