### ISSUE TITLE
Whole directory deletion is not appreciated

### ISSUE THREAD

**Issue by Silberling** [etiennestuder/gradle-jooq-plugin#63]
target {
		packageName = 'com.example.testabc.jooq'
		directory = 'src/main/java'
	}

deletes all content in "directory" without any notification or asking for confirmation.

I'd expect it to rebuild the innermost path including the package path. Therefore "jooq". If the user configures the project in such way he might lose important changes.

**Comment by etiennestuder** [comment]
Sharing output directories between different tasks, or mixing task outputs with static files is not recommended. See discussion [here](https://github.com/etiennestuder/gradle-jooq-plugin/issues/59).

**Comment by etiennestuder** [comment]
@Silberling As of v2.0.10, running the `clean` task does no longer implicitly remove any generated jOOQ sources.

**Comment by anthonyalayo** [comment]
@etiennestuder is it possible to allow turning the clean off as a feature? Even if it's not recommended, I would like to use existing directories without nuking other files.

**Comment by etiennestuder** [comment]
> @etiennestuder is it possible to allow turning the clean off as a feature? Even if it's not recommended, I would like to use existing directories without nuking other files.

This is very problematic, as I have explained in multiple threads. If you really want to have the generated sources in an existing directory containing other sources, I suggest you first generate the jOOQ sources into a unique directory and then copy them over from there to your destination directory, using the Gradle copy task.

**Comment by anthonyalayo** [comment]
Unfortunately I am quite a novice when it comes to gradle, so I am not sure how to say "run this copy step after the jooq plugin is done". Would there be something similar somewhere I can reference?

**Comment by etiennestuder** [comment]
I suggest you seek help on https://discuss.gradle.org/
