### ISSUE TITLE
target.directory property is not treated consistently

### ISSUE THREAD

**Issue by khanactl** [etiennestuder/gradle-jooq-plugin#65]
The Gradle clean task with this jooq plugin configured will erroneously wipe out the entire source directory when the directory property points to the root of a source path.

I have this as the target block in my jooq configuration in my gradle build file:

target {
  packageName = 'com.tll.mcorpus.db'
  // directory = 'src/main/java' // use to build from scratch
  directory = 'src/main/java/com/tll/mcorpus/db' // use to clean else src dir will get nixed!
}

If I run gradle generateMcorpusJooqSchemaSource and the directory property is set to '/src/main/java' (rather than 'src/main/java/com/tll/mcorpus'), the entire src/main/java gets deleted!

As I understand it from the Jooq-side, this directory property should point the source directory under which the jooq package will be 'inserted' WITHOUT the package path in this directory property path.

Am I missing something?

**Comment by etiennestuder** [comment]
Sharing output directories between different tasks, or mixing task outputs with static files is not recommended. See discussion [here](https://github.com/etiennestuder/gradle-jooq-plugin/issues/59).

**Comment by khanactl** [comment]
right - onto maven.

**Comment by etiennestuder** [comment]
@khanactl As of v2.0.10, running the `clean` task does no longer implicitly remove any generated jOOQ sources.
