### ISSUE TITLE
Introduce build service to provide JooqConfig

### ISSUE THREAD

**Issue by rpalcolea** [etiennestuder/gradle-jooq-plugin#652]
Hey @etiennestuder,

One of the challenges we are facing when using this plugin with things like testcontainers is that in order to configure the `JooqExtension` with a `JooqConfig` which in such case would require a running container which would need to happen in configuration phase which is far from ideal. Actually, this might be related to https://github.com/etiennestuder/gradle-jooq-plugin/issues/221 

Wondering if you have considered have a way for folks to plug their own build service and use that as a secondary mechanism to provide jooq configuration? or at least the jdbc information 

Would that be something that make sense for this plugin?

**Comment by etiennestuder** [comment]
Hi Roberto. I'm not sure I follow, but maybe it is related to [this question](https://github.com/etiennestuder/gradle-jooq-plugin/issues/614#issuecomment-1869653200).
