### ISSUE TITLE
Gradle clean task

### ISSUE THREAD

**Issue by farinexquebec** [etiennestuder/gradle-jooq-plugin#66]
I found out the hard way that gradle clean will delete the target directory specified in the jooq configuration.

On jooq website they use the following configuration as an example:
```
target {
                packageName = 'org.foo.bar'
                directory = 'src/main/java'
            }
```
But using this configuration will delete the java directory when executing gradle clean. Is it an intended behavior?

**Comment by etiennestuder** [comment]
Hi @farinexquebec. See comment thread in https://github.com/etiennestuder/gradle-jooq-plugin/issues/49.

**Comment by etiennestuder** [comment]
@farinexquebec As of v2.0.10, running the `clean` task does no longer implicitly remove any generated jOOQ sources.
