### ISSUE TITLE
`JooqGenerate` should implement `JavaExecSpec`

### ISSUE THREAD

**Issue by felixscheinost** [etiennestuder/gradle-jooq-plugin#660]
This is a feature request.

I think that `JooqGenerate` should implement `JavaExecSpec`. I think this wouldn't be too hard to achieve.

My use case would be debugging a `JooqGenerate` task using IntelliJ. If the task would implement that interface, IntelliJ automatically configures it to use the debugger running on a random port, as far as I know.

Would you be open to receive a PR for that change or do you see any problems implementing such a change?

**Comment by felixscheinost** [comment]
Just `JavaForkOptions` should be enough. https://github.com/JetBrains/intellij-community/blob/9ba394021dc73a3926f13d6d6cdf434f9ee7046d/plugins/gradle/tooling-extension-impl/src/org/jetbrains/plugins/gradle/tooling/internal/init/JvmDebugInit.gradle#L65

**Comment by etiennestuder** [comment]
Thanks for the issue. I took a brief look. Making that change would significantly widen the interface of the `JooqGenerate` class. I will not have the time to work on this in the near future, not implementing it nor reviewing a PR. I hope for your understanding.
