### ISSUE TITLE
Generate non-nullable Kotlin types through a precompiled script using kotlin DSL

### ISSUE THREAD

**Issue by NikolayMetchev** [etiennestuder/gradle-jooq-plugin#664]
I am trying to enable the non-null Kotlin generation but I don't see a way to do that in a precompiled script that uses kotlin DSL.
The example here doesn't work for precompiled scripts
https://github.com/etiennestuder/gradle-jooq-plugin#enforcing-the-jooq-configuration-xml-schema-version

Can we update the precompiled script example to also use kotlin dsl (not groovy) and show how to set these:
https://github.com/etiennestuder/gradle-jooq-plugin/tree/main/example/extract_precompiled_script_plugin

The attributes I want to set are:
        IsKotlinNotNullPojoAttributes = true
        isKotlinNotNullRecordAttributes = true
        isKotlinNotNullInterfaceAttributes = true

**Comment by etiennestuder** [comment]
Hi. I will not have time to look into this due to competing priorities. If someone submits a working PR for such an example using Kotlin, I will review it. I hope for your understanding.
