### ISSUE TITLE
generateJooq fails because `javaExecSpec` is null

### ISSUE THREAD

**Issue by chris-sloan** [etiennestuder/gradle-jooq-plugin#668]
I am trying to build a ktor service that connects to my mariadb database. The database already has a schema and data, so I'm trying to have jooq generate the model classes for me. 

But `generateJooq` fails when i try to build. I'm not able to get much from the error message, but when debugging I can see that `JooqGenerate.java` line 292, `javaExecSpec` is null. 

<img width="1301" alt="Screenshot 2023-11-30 at 18 54 21" src="https://github.com/etiennestuder/gradle-jooq-plugin/assets/9352594/c5567245-61f4-4fbf-954c-c9e4b2c11742">

Not really sure where to go from here, any pointers would be gratefully received. 
I've had a look through other issues and nothing really matches. There are warnings further up the ide error that talk about slf4j but i think they may be a red herring.

**Comment by chris-sloan** [comment]
I guess [this one](https://github.com/etiennestuder/gradle-jooq-plugin/issues/660) matches to a certain degree but I'm not sure where to start.

**Comment by etiennestuder** [comment]
`javaExecSpec` is null, unless your build configures it specifically, which is not often needed. See this [example](https://github.com/etiennestuder/gradle-jooq-plugin/blob/main/example/configure_jvm_args/build.gradle).

It seems the code generator was invoked but did not finish successfully.

I suggest running the same task from the cmd line to ensure the same issue occurs. You might also want to run the build from the cmd line with enough debug information to see the actual code generator invocation.
