### ISSUE TITLE
JOOQ doesn't generate classes unless schema is added or removed... problem with cache?

### ISSUE THREAD

**Issue by nikolavojicic** [etiennestuder/gradle-jooq-plugin#678]
I use JOOQ with Java-based Flyway migrations.

Issue repro steps:
- Start with empty database, without schemas
- Comment out `schema` in `jdbc` config (see below)
- Migrations are applied but JOOQ doesn't generate classes
- Re-run tasks - JOOQ still doesn't generate classes
- Uncomment `schema` in `jdbc` config and re-run tasks
- JOOQ generates classes this time, everything works fine
- Delete created schema in db to try again, re-run tasks
- Migrations are applied but JOOQ doesn't generate classes
- Re-run tasks - JOOQ still doesn't generate classes
- Comment out `schema` in `jdbc` config and re-run tasks
- JOOQ generates classes this time, everything works fine

(Specifying `schema` is not required because `inputSchema` is specified.)

Tried with `nu.studer.jooq` version `7.2` and `7.1.1`, both have the same problem.

JOOQ version: `ext['jooq.version'] = '3.16.4'`.

```groovy
jooq {
    configurations {
        main {
            generateSchemaSourceOnCompilation = true

            generationTool {
                logging = org.jooq.meta.jaxb.Logging.WARN
                jdbc {
                    driver = 'org.postgresql.Driver'
                    url = 'jdbc:postgresql://localhost:5432/some_db'
                    user = 'some_user'
                    password = 'some_password'
                    // schema = 'some_schema'
                }
                generator {
                    name = 'org.jooq.codegen.DefaultGenerator'
                    database {
                        name = this.databaseMetaName()
                        excludes = 'flyway_schema_history'
                        inputSchema = 'some_schema'
                        forcedTypes {
                            forcedType {
                                name = 'INSTANT'
                                includeTypes = '(?i:TIMESTAMP\\ WITH\\ TIME\\ ZONE)'
                            }
                        }
                    }
                    strategy {
                        matchers {
                            tables {
                                table {
                                    tableIdentifier {
                                        transform = 'UPPER'
                                        expression = '$0'
                                    }
                                    tableClass {
                                        transform = 'PASCAL'
                                        expression = '$0_Table'
                                    }
                                    pojoClass {
                                        transform = 'PASCAL'
                                        expression = '$0'
                                    }
                                }
                            }
                            fields {
                                field {
                                    fieldGetter {
                                        transform = 'CAMEL'
                                        expression = '$0'
                                    }
                                    fieldSetter {
                                        transform = 'CAMEL'
                                        expression = '$0'
                                    }
                                }
                            }
                        }
                    }
                    generate {
                        pojosAsJavaRecordClasses = true
                        relations = true
                        deprecated = false
                        records = true
                        pojos = true
                        fluentSetters = true
                        javaTimeTypes = true
                    }
                    target {
                        packageName = 'some.path.generated'
                    }
                }
            }
        }
    }
}

tasks.named('generateJooq').configure { allInputsDeclared = true }
```

Gradle task looks like this:

```groovy
task migrateProject(dependsOn: [migrateSomeSchema, clean, assemble]) {
    assemble.mustRunAfter(clean, migrateSomeSchema)
}
```

It seems to me that adding and removing that `schema` property after each failure evicts some cache and fixes the problem. If I could cause that eviction programmatically in `migrateProject` task that would also be helpful as a temporary workaround.

**Comment by etiennestuder** [comment]
The jOOQ Gradle task does not inspect your DB for changes. Instead you need to provide the Gradle task with extra inputs based on which the task will either run the code generation or not. A typical input are the DB schema files, as demonstrated in the example linked below.

See here for a complete example:
https://github.com/etiennestuder/gradle-jooq-plugin/tree/main/example/configure_jooq_with_flyway

**Comment by nikolavojicic** [comment]
Thanks for answer.

Adding `migration` path (to Java-based migrations) didn't solve my issue:

```groovy
tasks.named('generateJooq').configure {
    allInputsDeclared = true
    inputs
            .files(fileTree('src/main/java/db/migration'))
            .withPropertyName('migrations')
            .withPathSensitivity(PathSensitivity.RELATIVE)
}
```

Code generation task is actually executed each time in my case anyway: project is `clean`ed, schemas are `migrate`d and then `assemble` is called (after both clean and migrate) - which should trigger JOOQ generation... in the console I get: `Task :...:generateJooq` and an empty `generated-src/jooq` directory is generated.

Project is a little bit more complicated than the example as it is modular monolith with schema per module and Java based migrations etc. We have a project with the same structure working fine but with SQL based migrations.
