### ISSUE TITLE
Combination of setup-gradle github action with cache and gradle-jooq-plugin leads to "Unresolved reference"

### ISSUE THREAD

**Issue by mrclrchtr** [etiennestuder/gradle-jooq-plugin#682]
Hi, first of all, thank you very much for the plugin!

I use the plugin and [setup-gradle](https://github.com/gradle/actions/tree/main/setup-gradle) in combination.

I have configured the plugin as follows:
```
jooq {
  configurations {
    create("main") {
      jooqConfiguration.apply {
        logging = org.jooq.meta.jaxb.Logging.WARN
        jdbc.apply {
          driver = "org.postgresql.Driver"
          url = "jdbc:postgresql://localhost:54320/service"
          user = "service"
          password = "password"
        }
        generator.apply {
          name = "org.jooq.codegen.KotlinGenerator"
          database.apply {
            name = "org.jooq.meta.postgres.PostgresDatabase"
            inputSchema = "public"
          }
          target.apply {
            packageName = "de.mrclrchtr.generated.persistence.entities"
          }
          strategy.apply {
            name = "org.jooq.codegen.DefaultGeneratorStrategy"
            matchers = Matchers().withTables(
              MatchersTableType().withTableClass(
                MatcherRule()
                  .withTransform(MatcherTransformType.PASCAL)
                  .withExpression("\$0_TABLE")
              )
            )
          }
          generate.apply {
            isKotlinNotNullRecordAttributes = true
            isGeneratedAnnotation = true
            indentation = "\\s\\s"
            isSequences = true
          }
        }
      }
    }
  }
}

tasks.named<JooqGenerate>("generateJooq") {
    // Run the Flyway migration before generating the jOOQ sources
    dependsOn(":infrastructure:flywayComposeUp")

    // Make jOOQ task participate in incremental builds (and build caching)
    allInputsDeclared.set(true)

    // Declare Flyway migration scripts as inputs on the jOOQ task
    inputs.files(fileTree("$projectDir/src/main/resources/db/migration"))
      .withPropertyName("migrations")
      .withPathSensitivity(PathSensitivity.RELATIVE)
  }
```

In the pipeline I get:
`Task :service:generateJooq FROM-CACHE`

and then many errors of this type:
```
> Task :holz-service:compileKotlin FAILED
e: file:///home/runner/_work/service/src/main/kotlin/de/***/domain/Service.kt:5:26 Unresolved reference: generated
```

So not even the package `generated` was pulled from the cache.

What could be the reason? This should actually work, right?

Thank you very much for your help!

**Comment by etiennestuder** [comment]
It could be that what you have in the cache is not the fully generated sources, which can happen if you underspecify the inputs to the jOOQ task and then run the build with build caching enabled.

I suggest you run the build with `--rerun-tasks`, which will repopulate the cache, and then run it again but this time without `--rerun-tasks.` I would do all this locally, i.e., outside of GitHub, to minimize external influences while debugging.

If the above works properly, your issue might be related to GiHub action and what it has stored in the directory of the local build cache (possibly the same problem as what you tried to rule out with the experiment above).

I suggest running all your builds with [Build Scan enabled](https://scans.gradle.com/) to get more insights into what is happening.

**Comment by mrclrchtr** [comment]
Thanks for the advice.
