### ISSUE TITLE
Is it possible to override generateRecordClassFooter in JavaGenerator without a new project?

### ISSUE THREAD

**Issue by aram535** [etiennestuder/gradle-jooq-plugin#69]
Just figured I'd check this before I jumped in.  Do I need to create a new project (or sub-project) to override generateRecordClassFooter in JavaGenerator?  I'd figured it would be an easier way to do this in-line in the same build.gradle file as the main project.

**Comment by aram535** [comment]
Hi - Understood ... it's possible that I may need to create a whole generator override like you have in project: .../example/use_custom_generator 

Let's wait for Lukas to see what the recommended method is.  Not sure one I'd hate more, to have to have an inner project with an override of the generator class or writing static helper classes.

**Comment by lukaseder** [comment]
Indeed, the [example you've mentioned](https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/use_custom_generator) seems the way to go here. Looks like creating that sub-project / module is way easier in Gradle than in Maven ([see the additional build.gradle file here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/use_custom_generator/custom-generator/build.gradle)), so I guess this isn't really as much of an issue in Gradle.

**Comment by etiennestuder** [comment]
Note that due to Gradle's incrementalness, the project with the custom generator will only be built when it actually changes. So no overhead in terms of performance to have this in a separate project.

**Comment by etiennestuder** [comment]
Thanks for your reply above, @lukaseder .

**Comment by aram535** [comment]
Thank you @etiennestuder @lukaseder
