### ISSUE TITLE
[Question] How is the `cleanGenerateJooq` created?

### ISSUE THREAD

**Issue by lfgcampos** [etiennestuder/gradle-jooq-plugin#695]
I am trying to understand how such a task is created.
Task I a talking about is the one mentioned [here](https://github.com/etiennestuder/gradle-jooq-plugin?tab=readme-ov-file#deleting-the-generated-jooq-sources).

I can use it without any problems on my project even though it doesn't show on my gradle tasks options - not on intellij, not on `gradlew tasks`, but it kinda "shows up" if I run `./gradlew help --task cleanGenerateJooq`.

I've tried to check in the plugin code how that is created without any luck.

This might be a gradle question after all, apologies if that is the case.
But it would definitely help me understanding how it all works together.

**Comment by etiennestuder** [comment]
These _clean_ tasks are created via task rules, which are a concept of Gradle. Some task rules, like the ability to clean the output(s) of a task, are automatically created by Gradle. There is nothing done specifically by the gradle-jooq plugin.

**Comment by lfgcampos** [comment]
Thank you very much @etiennestuder - a learning for me.
