### ISSUE TITLE
Official jOOQ codegen gradle plugin support now in 3.19?

### ISSUE THREAD

**Issue by Anurag--Singh** [etiennestuder/gradle-jooq-plugin#697]
Great work :-),

How is your plugin different from the one introduced **[in official]** (https://www.jooq.org/doc/3.19/manual/code-generation/codegen-gradle/)?

Thank you

**Comment by Anurag--Singh** [comment]
@etiennestuder  Could you please respond?

**Comment by etiennestuder** [comment]
1. This question come up before. Please check previous, closed GitHub Issues.
2. Given my plugin was first, I suggest asking your question on the jOOQ forum for how theirs is different from mine.

**Comment by Anurag--Singh** [comment]
Thank you for the prompt reply. As suggested, I will consider it.
