### ISSUE TITLE
Classpath Issues with Custom Generator

### ISSUE THREAD

**Issue by 67726e** [etiennestuder/gradle-jooq-plugin#7]
I am trying to use a custom jOOQ generator class to alter the generate source code, but when I run with the class specified I am getting the following:

```
java.lang.ClassNotFoundException: us.hexcoder.CustomJooqGeneratorStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jooq.util.GenerationTool.loadClass(GenerationTool.java:492)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:231)
	at org.jooq.util.GenerationTool$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at nu.studer.gradle.jooq.JooqTask.generate(JooqTask.groovy:38)
```

I have written up a [StackOverflow post](http://stackoverflow.com/questions/29988281/gradle-task-classpath) describing the situation, but am not getting any luck with the issue. Given that I'm not quite sure where the issue lies at this point (in my Gradle configuration, in this plugin, or in jOOQ) I'm posting here as well. I have also have a minimal recreation of the issue up on [GitHub](https://github.com/67726e/test-jooq) - you'll need to create a Postgres DB with the credentials in the `build.gradle` file, but running `gradle jar` will achieve the exception. Looking through the logs with the `--debug` switch, it looks like the JAR is in fact being picked up:

```
19:13:28.857 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Visiting dependency :test-jooq:unspecified(classpath) -> :test-jooq-generator:(dependency: #test-jooq-generator; {classpath=[default]})
19:13:28.858 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version :test-jooq-generator:
19:13:28.858 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Attempting to resolve :test-jooq-generator: using repositories [BintrayJCenter, MavenRepo, flatDir]
19:13:28.858 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module ':test-jooq-generator:' in resolver cache 'BintrayJCenter'
19:13:28.859 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module ':test-jooq-generator:' in resolver cache 'MavenRepo'
19:13:28.862 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/private/tmp/test-jooq/lib/test-jooq-generator-.jar
19:13:28.863 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/private/tmp/test-jooq/lib/test-jooq-generator.jar
19:13:28.866 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] Found artifact but no meta-data for module ':test-jooq-generator:' in repository 'flatDir', using default meta-data.
19:13:28.866 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainDependencyResolver] Using :test-jooq-generator: from Ivy repository 'flatDir'
```

Any pointers?

**Comment by bleppard** [comment]
I am running into this issue. Any update on how to resolve this?

**Comment by etiennestuder** [comment]
I have not looked into it, given it was closed by the reporter.

**Comment by etiennestuder** [comment]
@bleppard Did you add `us.hexcoder.CustomJooqGeneratorStrategy` to the `jooqRuntime` configuration? (see https://github.com/etiennestuder/gradle-jooq-plugin#defining-your-database-drivers)

**Comment by 67726e** [comment]
@bleppard You'll have to forgive me as the issue is nearly two years old and I was going on 16+ hour per day coding binges back then for a startup so. I genuinely have no idea what I was working on. In fact I just pulled up the relevant `build.gradle` I would have been working on at the time and it does not even contain a custom generation strategy.

**Comment by bleppard** [comment]
@etiennestuder Thanks for the quick response. The custom generator is in my project, I haven't broken it out into a separate module on JCenter and would prefer not to have to do that.. 

Per http://stackoverflow.com/a/33192131/262789, I am using buildSrc to compile the custom generator. Although, I know the StackOverflow answer doesn't pertain to this plugin. It seems like using `buildSrc` should still work, but I still am getting `ClassNotFoundException`. I am not sure how to use `jooqRuntime` in this case.

**Comment by bleppard** [comment]
No problem @67726e, I am also working on a startup. Some days I don't remember what I was working on the night before, much less a couple of years ago. 

I appreciate you looking through the logs for me.

**Comment by etiennestuder** [comment]
@bleppard You do not necessarily have to break it out into a separate module that is stored on jcenter. You can also have a module within your Gradle project that builds the jar and then you add that jar to the `jooqRuntime` configuration. I'll see if we can post an example in the next few days.

**Comment by etiennestuder** [comment]
@bleppard I've added a full example on how to include a custom generator strategy that is defined in source form in the same Gradle project where it is being applied:

https://github.com/etiennestuder/gradle-jooq-plugin/tree/master/example/use_custom_generator

**Comment by felipefzdz** [comment]
@bleppard And you can also find an automated test that exercises this scenario [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/b4e8aefda236557b35ada77d8474798e808488ec/src/test/groovy/nu/studer/gradle/jooq/JooqFuncTest.groovy#L101-L101)

**Comment by bleppard** [comment]
@felipefzdz That worked perfectly thanks.
