### ISSUE TITLE
add attribute flag to configure whether `generateSampleJooqSchemaSource` is dependency of `compileJava`

### ISSUE THREAD

**Issue by ziliangpeng** [etiennestuder/gradle-jooq-plugin#70]
I have a use case where I don't want `compileJava` to run `generateSampleJooqSchemaSource` automatically because I'm generating DB classes in a one-off, and don't want the task run in our CI system.

What's your thought about adding a flag so user can decide whether he/she wants the task dependency?

**Comment by etiennestuder** [comment]
See https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/remove_task_dependency/build.gradle
