### ISSUE TITLE
@TypeDef works but @Type does not with a package-java.info

### ISSUE THREAD

**Issue by 18anandn** [etiennestuder/gradle-jooq-plugin#701]
I am using codegen version 7.0 with JOOQ version 3.16.6 in Kotlin.

I have a custom type defined over some entities as follows 
```
@TypeDef(name = "json_string", typeClass = JsonStringType::class)
```

The codegen works as expected. But when I move it to a `packege-info.java` within a subpackage in the same module, the codegen is not able to pick up the class.

When using @TypeDef over an entity, I can see the following in the logs

> 16:46:28.748 [main] DEBUG org.hibernate.boot.internal.ClassLoaderAccessImpl - No temp ClassLoader provided; using live ClassLoader for loading potentially unsafe class : org.example.common.storage.postgres.dialect.JsonStringType

But when putting it inside a `package-info.java`. I get the following

> 16:55:54.070 [main] DEBUG org.hibernate.boot.internal.ClassLoaderAccessImpl - No temp ClassLoader provided; using live ClassLoader for loading potentially unsafe class : json_string

The following is the `package-java.info`
```
@TypeDef(name = "json_string", typeClass = JsonStringType.class)
package org.example.myservice.storage.entity;

import org.example.common.storage.postgres.dialect.JsonStringType;
import org.hibernate.annotations.TypeDef;
```

and the column
```
@Type(type = "json_string") @Column(nullable = false) val parsedValue: String,
```

cc: @lukaseder

**Comment by etiennestuder** [comment]
I'm sorry but I cannot help with this. Maybe submit a self-contained sample project that exposes the issue to the jOQQ project.
