### ISSUE TITLE
Option to disable schema generation on compileJava

### ISSUE THREAD

**Issue by prusik** [etiennestuder/gradle-jooq-plugin#8]
Hello,

It would be nice to have the option to disable schema generation on compileJava. I wrote a workaround using this code, which works but i'm afraid the schema would eventually get updated on the CI server (if we mistakenly rename the schema name "demo'" and forget to change the compileJava code, for example). In my case, I only want this tool available in the dev environment.

compileJava {
    //This prevents the jooq data model from being generated automatically every time gradle
    //compiles java code.
    compileJava.taskDependencies.values -= "generateDemoJooqSchemaSource"
}

On another note, thanks for the plugin, works like a charm!
shaun

**Comment by dadmin-admin** [comment]
+1

**Comment by fedotxxl** [comment]
+1

**Comment by bosakm** [comment]
+2

**Comment by oehme** [comment]
I don't think this plugin needs a special functionality for this. Just use some code in your build script:

```
generateDemoJooqSchemaSource.enabled = whateverConditionYouCanDreamOf
```

**Comment by etiennestuder** [comment]
I'd like to keep up the default behavior of having a dependency on code generation from the compilation task, since this is what you typically want to have. The solution suggested above by @oehme works well for disabling the task under certain conditions (like the env being CI).
