### ISSUE TITLE
The task 'cleanGenerateSampleJooqSchemaSource' remove the incorrect directory

### ISSUE THREAD

**Issue by shellwalker** [etiennestuder/gradle-jooq-plugin#87]
When I execute the command `./gradlew generateSampleJooqSchemaSource` twice or more, it always show the same prompt message **`up-to-date`**
```shell
➜  jooq git:(master) ✗ ./gradlew generateSampleJooqSchemaSource

BUILD SUCCESSFUL in 0s
1 actionable task: 1 up-to-date
```
So, I execute the command `./gradlew cleanGenerateSampleJooqSchemaSource` to clean the generated code. As I expected, it will only remove the content under **`target/directory/target/package/name`**. **BUT**, it remove the directory **`target/directory`** where my other source code(with different package name) under this directory(eg: **`src/main/java`**).

The following is my `jooq` configuration and its execution result.

```gradle
jooq {
    version = '3.11.5'
    edition = 'OSS'
    sample(sourceSets.main) {
        jdbc {
            // datasource configuration
            driver = 'com.mysql.jdbc.Driver'
            url = 'jdbc:mysql://localhost:3306'
            user = 'root'
            password = ''
        }
        generator {
            //jOOQ library <= 3.10.x: gradle-jooq plugin 2.0.11
            //jOOQ library >= 3.11.x: gradle-jooq plugin 3.0.0 or higher
            // If plugin version 2.0.x
//            name = 'org.jooq.util.DefaultGenerator' // Plugin 2.0.11
            // else
            name = 'org.jooq.codegen.DefaultGenerator' // Plugin 3.0.2
            database {
//                name = 'org.jooq.util.mysql.MySQLDatabase'
                name = 'org.jooq.meta.mysql.MySQLDatabase'
                includes = '.*'
                excludes = ''
                inputSchema = 'jooq' // Database name
            }
            target {
                directory = 'src/main/java'
                packageName = 'com.company.jooq.autogen'
                clean = true
            }
        }
    }
}
```

```shell
➜  jooq git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        src/main/java/com/company/jooq/autogen/

nothing added to commit but untracked files present (use "git add" to track)
➜  jooq git:(master) ✗ ./gradlew cleanGenerateSampleJooqSchemaSource

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
➜  jooq git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    src/main/java/com/company/jooq/JooqApplication.java

no changes added to commit (use "git add" and/or "git commit -a")
```
The `java` directory is removed after executing task `cleanGenerateSampleJooqSchemaSource`.
![image](https://user-images.githubusercontent.com/23768098/47477488-0fe22280-d858-11e8-96ef-7fb20babc52c.png)

**Comment by shellwalker** [comment]
```
jooqRuntime - The classpath used to invoke the jOOQ generator. Add your JDBC drivers or generator extensions here.
+--- org.jooq:jooq-codegen -> 3.11.5
|    +--- org.jooq:jooq:3.11.5
|    |    \--- javax.xml.bind:jaxb-api:2.2.12 -> 2.3.1
|    |         \--- javax.activation:javax.activation-api:1.2.0
|    \--- org.jooq:jooq-meta:3.11.5
|         \--- org.jooq:jooq:3.11.5 (*)
\--- mysql:mysql-connector-java -> 5.1.47

```

**Comment by etiennestuder** [comment]
Which jooq plugin version, not which jooq dependency versions.

**Comment by etiennestuder** [comment]
I cannot reproduce this. I see it properly deleting only the directory you have specified under `target.directory`. Please provide a self-contained example showing the issue.

**Comment by shellwalker** [comment]
Code is here https://github.com/shellwalker/jooqsample.

After execute the `./gradlew cleanGenerateCloudhisJooqSchemaSource`, I think it should only remove the content under `src/main/java/com/ewellhealth/jooq/autogen/`, not `src/main/java`.

**Comment by etiennestuder** [comment]
@shellwalker Thanks for the sample project. If you set the target directory to `src/main/java`, that's what gets deleted when you call `cleanGenerateCloudhisJooqSchemaSource ` - regardless of what package name you configure. See [this issue](https://github.com/etiennestuder/gradle-jooq-plugin/issues/59) for an extended discussion. I do not intend to change this behavior. I can highly recommend to generate the jooq sources into a different, non-shared source folder and add the sources to the source set that already contain src/main/java, as mentioned in that other issue.
