### ISSUE TITLE
Configuration for gradle implementation/api fail

### ISSUE THREAD

**Issue by ayush-finix** [etiennestuder/gradle-jooq-plugin#88]
Plugin version: 3.0.2
jooq version: 3.11.7

When configuring dependencies with api/implementation, the jooq generate task fails with 
`Unable to instantiate JDBC driver: org.postgresql.Driver => Check whether the jar file is present`
Example of failing dependency settings.
```
<api or implementation> group: 'org.postgresql', name: 'postgresql', version: '42.2.5'
jooqRuntime 'org.postgresql:postgresql:42.2.5'
```
changing to the compile configuration works fine though with no other changes
```
compile group: 'org.postgresql', name: 'postgresql', version: '42.2.5'
jooqRuntime 'org.postgresql:postgresql:42.2.5'
```
We've tried with both the java and java-library plugins.

**Comment by etiennestuder** [comment]
@ayush-finix Adding the postgres dependency to `jooqRuntime` is the right thing to do. Only the dependencies that are part of the `jooqRuntime` configuration are available on the classpath of the process that executes the jOOQ source code generation.

**Comment by ayush-finix** [comment]
@etiennestuder Hey, thanks for responding!
I wasn't talking about the jooqRuntime part. Gradle is deprecating the `compile` config in favor of using `implementation` or `api` depending on your use case. https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation and https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle

However, the plugin fails if you change `compile` to `implementation` in your build.gradle.

**Comment by etiennestuder** [comment]
Please provide a self-contained running example and I will take a look.
