### ISSUE TITLE
jooq upgrade in current release

### ISSUE THREAD

**Issue by jottyfan** [etiennestuder/gradle-jooq-plugin#90]
as discussed in https://github.com/jOOQ/jOOQ/issues/8160 , we need another new release to omit error warnings of the current one if using postgresql 11. Could you please release a such one? The change should be simply switching the jooq version number from 3.11.2 to 3.11.8 ( https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/gradle.properties#L7 ).

Thx.

**Comment by etiennestuder** [comment]
I plan to release a new version next week.

**Comment by jottyfan** [comment]
fantastic, thank you!

**Comment by etiennestuder** [comment]
@jottyfan One thing I don't understand: why don't you just bumb up the jOOQ version to be used as described [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#specifying-the-jooq-version-and-edition)?

**Comment by etiennestuder** [comment]
Fixed on master. The upcoming release will have the currently more recent version of jOOQ configured as the default. Closing this issue.

**Comment by jottyfan** [comment]
> @jottyfan One thing I don't understand: why don't you just bumb up the jOOQ version to be used as described [here](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#specifying-the-jooq-version-and-edition)?

Shame on me, I didn't look up the docs for overwriting default values. Thanks for the hint, I need to be less lazy in RTFM... 👍
