### ISSUE TITLE
Disabling code generation if SQL didn't change

### ISSUE THREAD

**Issue by Jolter** [etiennestuder/gradle-jooq-plugin#93]
I'm looking at a setup where the database is in a Docker container, defined in the same project as my Java code.
So, before running the jooq generation, the Gradle build needs to start the DB container - then clean up that container after running the code gen. I'm using the 'com.bmuschko.docker-remote-api' to instrument the Dockers.

The database schema is defined in an SQL file in the same repo, and automatically applied to the DB container on bootup.
We have it working pretty well, the only problem is that the whole "set up DB->jooq->tear down DB" chain runs every time. 

```
generateMyJooqSchemaSource{
    dependsOn(startDbContainer)
    finalizedBy (teardownDbContainer)
}
```

What I would love would be to be able to declare somehow the SQL file as input - ie that the jOOQ build does not need to happen unless the outputs are missing, or the SQL file changed since the last build.

Probably this is possible by carefully declaring task dependencies and inputs/outputs but I've been struggling with it for a while now without success. Not least, because the Docker tasks declare no outputs so are never considered up-to-date. 

Any advice?

**Comment by etiennestuder** [comment]
Hi @Jolter. This is how we do it in our own build conceptually. Please adjust to your needs.

```
tasks.named("generateMainJooqSchemaSource").configure {
        outputs.cacheIf { true }
        inputs.files(project.fileTree('src/main/resources/jooq'))
            .withPropertyName("migrations")
            .withPathSensitivity(PathSensitivity.RELATIVE)
}
```

That task will only run if the jooq files have changed. It also gives us build caching support.

Please note that Gradle also has the concept of [finalizer tasks](https://docs.gradle.org/current/dsl/org.gradle.api.Task.html#org.gradle.api.Task:finalizedBy). They come in handy when you have to run some setup and tear down before/after the actual work.

**Comment by Jolter** [comment]
Hi @etiennestuder,
Thanks for answering so quickly!
If I understand your answer correctly, you have the SQL files in the `resources/jooq` directory, and the plugin will understand that it doesn't need to rerun the generate task if the SQL files didn't change.
I didn't understand the next two lines but I am guessing they are only relevant to your particular build?

I tried this approach and I found that it works fine:
```
> Task :ws:generateMyJooqSchemaSource UP-TO-DATE
Skipping task ':ws:generateMyJooqSchemaSource' as it is up-to-date.
```

So, now I only have to figure out how to stop the `startDbContainer` task from running in this case. Because `:ws:generateMyJooqSchemaSource` depends on it, it will always run even if `:ws:generateMyJooqSchemaSource` is up-to-date.

I suppose this is not really a problem with your plugin, it's more related to Gradle in general and `bmuschko/gradle-docker-plugin`. I'll see if I can find some way to disable that task in case `:ws:generateMyJooqSchemaSource` is up-to-date. Generally, Gradle doesn't seem to like doing that because the up-to-datedness is only calculated at task execution time, and then it's too late to disable the dependency tasks (they already executed).

**Comment by etiennestuder** [comment]
> If I understand your answer correctly, you have the SQL files in the `resources/jooq` directory, and the plugin will understand that it doesn't need to rerun the generate task if the SQL files didn't change.

Yes.

> I didn't understand the next two lines but I am guessing they are only relevant to your particular build?

- `.withPropertyName("migrations")` just gives the input a name
- `.withPathSensitivity(PathSensitivity.RELATIVE)` means if someone checks out the project to a different location (i.e. all absolute paths will be different), cached outputs can still be reused as long as the relative path is the same. Reading [this](https://docs.gradle.org/5.2/userguide/build_cache.html#enable_caching_of_non_cacheable_tasks) will be informative for you.

> I suppose this is not really a problem with your plugin, it's more related to Gradle in general and `bmuschko/gradle-docker-plugin`. I'll see if I can find some way to disable that task in case `:ws:generateMyJooqSchemaSource` is up-to-date. Generally, Gradle doesn't seem to like doing that because the up-to-datedness is only calculated at task execution time, and then it's too late to disable the prerequisite tasks (they already executed).

There is currently no public API in Gradle for this. Maybe you could create a new docker task that brings up the database and make the jooq files inputs of that task (like you did for the jooq).

We do not have this problem in our build because developers do not run the db via docker but have it installed locally, thus no db to spin up before potentially running tests.

**Comment by etiennestuder** [comment]
I'm closing this issue given the original questions has been answered.

**Comment by Jolter** [comment]
Thanks Etienne, you've been very helpful!
