### ISSUE TITLE
Do not regenerate jooq code at every build

### ISSUE THREAD

**Issue by dantonini** [etiennestuder/gradle-jooq-plugin#94]
Hi, 
I would like to manually control when jooq code is generated. Usually I generate jooq code in src and commit in version control, then manually regenerate when I update the ddl (my schema is quite large and I want speed up the CI server). Actually the jooq generation process happens every time I use:

gradle clean build

Is there a way to NOT register jooq generation task as implicit dependency of compileJava task?

Cheers

**Comment by ahamana** [comment]
@dantonini The way is explained on the README.

\----------------------------------------
Removing the implicit task dependency between the compile task and the jOOQ source generation task: here.

The build.gradle sample is [here.](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/example/remove_task_dependency/build.gradle)
\----------------------------------------

**Comment by dantonini** [comment]
Thank you!

I completely miss that line.

Cheers

**Comment by etiennestuder** [comment]
@dantonini @ahamana You can also just create a new source set and have the generated jooq sources be part of that source set. You will still get Gradle tasks to compile the sources but they will not run as part of invoking the `build` / `assemble` task.

```
jooq {
    sample(sourceSets.create('jooq') {
    ...
    }
}
```

**Comment by Anurag--Singh** [comment]
I am using `generateSchemaSourceOnCompilation = false` for the mentioned problem. It is not working for me. Am I interpreting it wrong?

I don't want to generate/regenerate code automatically at every build. I will leave that to CI/CD to decide based upon environment either dev, stage or prod etc.

I know the steps how to define multiple configurations in jooq but not stop it  from executing at every build time.

**Comment by etiennestuder** [comment]
The flag `generateSchemaSourceOnCompilation` controls whether a dependency between the task compiling the sources and the jooq task generating the sources is wired in or not.

https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/src/main/groovy/nu/studer/gradle/jooq/JooqPlugin.java#L54
