### ISSUE TITLE
Cannot change jooq version

### ISSUE THREAD

**Issue by ieugen** [etiennestuder/gradle-jooq-plugin#95]
Hello,

I can't change the version used by jooq to the latest `3.11.10` . 
I followed the instructions in https://github.com/etiennestuder/gradle-jooq-plugin#defining-the-jooq-version-when-the-spring-boot-plugin-is-applied .

It does not work. I don't use the management plugin. I use `gradle 5.2.1` and `id 'nu.studer.jooq' version '3.0.3'`

```
ext['jooq.version'] = '3.11.10'

jooq {
    version = '3.11.10'
...
```

I have a multi modul gradle build that handles two things: 
- apply migrations with flyway
- generate jooq bindings

```
.
├── build
├── build.gradle
├── core-db
├── core-db-migrations
├── gradle
├── gradlew
└── settings.gradle
```

**Comment by lukaseder** [comment]
Just to be sure, there's a known issue related to the version that is displayed in the logs when loading jOOQ: https://github.com/jOOQ/jOOQ/issues/8427

**Comment by ieugen** [comment]
Thanks. I think that is the case.
