### ISSUE TITLE
Cannot run generateJooqSchemaSource task with JOOQ 3.11.11

### ISSUE THREAD

**Issue by yissachar** [etiennestuder/gradle-jooq-plugin#97]
I get the following:

```
Error: Could not find or load main class org.jooq.codegen.GenerationTool
```

The same for 3.11.10. I was only able to get it working with 3.11.9 but unfortunately I need 3.11.11 since it has bug fixes that I need.

**Comment by yissachar** [comment]
May be related to https://github.com/jOOQ/jOOQ/issues/7419?

**Comment by etiennestuder** [comment]
I cannot reproduce this. All integration tests of the plugin pass with 3.11.11 without any code or test changes. Also, we are successfully using gradle-jooq-plugin 3.0.3 with jOOQ 3.11.11 in our project.

**Comment by yissachar** [comment]
This was a misunderstanding on my part - I hadn't updated the types in my config, e.g. `'org.jooq.util.DefaultGenerator'` had to become `'org.jooq.codegen.DefaultGenerator'`. Sorry for the trouble.
